import '@testing-library/jest-dom/vitest';
import { render,screen,within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { vi,describe,it,expect } from 'vitest';
import { CollapsibleSourceList } from './collapsible-source-list';
import type { SummarySource } from '@/lib/api/types';
const src=(n:number):SummarySource=>({type:'note',id:`note_${n}`,occurred_at:`2026-07-${String(n).padStart(2,'0')}T09:00:00Z`,label:`Source ${n}`,excerpt:`Excerpt ${n}`});
const setup=(count:number|null)=>{const onOpen=vi.fn();render(<CollapsibleSourceList sources={count===null?null:Array.from({length:count},(_,i)=>src(i+1))} onOpenNote={onOpen}/>);return onOpen};
describe('CollapsibleSourceList',()=>{
 it('normalizes zero and null sources to no source section',()=>{setup(0);expect(screen.queryByRole('heading',{name:'Source notes'})).not.toBeInTheDocument();setup(null);expect(screen.queryByRole('heading',{name:'Source notes'})).not.toBeInTheDocument();});
 it('renders one and exactly five sources without an expand control',()=>{setup(1);expect(screen.getByText('Source 1')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Show all/})).not.toBeInTheDocument();setup(5);expect(screen.getByText('Source 5')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Show all/})).not.toBeInTheDocument();});
 it('shows the first five of six sources, preserves API order, expands and collapses',async()=>{setup(6);expect(screen.getAllByRole('listitem').map(li=>within(li).getByText(/Source/).textContent)).toEqual(['Source 1','Source 2','Source 3','Source 4','Source 5']);expect(screen.queryByText('Source 6')).not.toBeInTheDocument();const toggle=screen.getByRole('button',{name:'Show all 6 sources'});expect(toggle).toHaveAttribute('aria-expanded','false');expect(toggle).toHaveAttribute('aria-controls');await userEvent.click(toggle);expect(toggle).toHaveAttribute('aria-expanded','true');expect(screen.getByText('Source 6')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Show fewer 6 sources'}));expect(screen.queryByText('Source 6')).not.toBeInTheDocument();});
 it('expands 30 sources inline and more than 30 in a bounded keyboard-focusable vertical region',async()=>{setup(30);await userEvent.click(screen.getByRole('button',{name:'Show all 30 sources'}));expect(screen.getByText('Source 30')).toBeInTheDocument();expect(document.querySelector('.source-scroll-region')).toBeNull();setup(31);await userEvent.click(screen.getByRole('button',{name:'Show all 31 sources'}));const region=screen.getByLabelText('All source notes');expect(region).toHaveClass('source-scroll-region');expect(region).toHaveAttribute('tabindex','0');expect(screen.getByText('Source 31')).toBeInTheDocument();});
 it('does not open notes until source action click and keeps expansion after close-like rerender',async()=>{const onOpen=setup(6);expect(onOpen).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Show all 6 sources'}));await userEvent.click(screen.getAllByRole('button',{name:'Open source note'})[5]);expect(onOpen).toHaveBeenCalledTimes(1);expect(screen.getByText('Source 6')).toBeInTheDocument();});
});
