import { ApiRequestError,apiRequest } from './client';
import type { Action, ActionList, ActionListParams, ActionStatus, AskRequest, AskResponse, NormalizedAskResponse, LoginRequest, NoteCreated, NoteDetail, NotesHistory, NotesHistoryParams, PeopleList, PeopleListParams, PersonWorkspaceDetail, PersonMergeRequest, PersonMergeResponse, UpdatePersonRequest, UpdatePersonResponse, RegisterRequest, TicketsList, TicketsListParams, TicketWorkspaceDetail, SessionData, SummariesList, SummariesParams, SummaryDetail, SummaryGenerateRequest, SummaryGenerateResult, TelegramLink, TelegramStatus, Today } from './types';
function qs(params:NotesHistoryParams|PeopleListParams|TicketsListParams|ActionListParams|SummariesParams){const sp=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')sp.set(k,String(v))});const q=sp.toString();return q?`?${q}`:''}
function isObject(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==='object'&&!Array.isArray(v)}
function malformedSummaryError(){return new ApiRequestError({kind:'unexpected_error',message:'This summary could not be displayed completely.'})}
function unwrapSummaryResponse(response:unknown):SummaryDetail{const apiSummary=isObject(response)&&isObject(response.data)&&isObject(response.data.summary)?response.data.summary:null;if(!apiSummary)throw malformedSummaryError();return apiSummary as SummaryDetail}
export function normalizeAskResponse(response:AskResponse):NormalizedAskResponse{
 const status=response.status??(response.confidence==='insufficient_context'||response.confidence==='insufficient'?'insufficient_context':response.confidence==='ambiguous'?'ambiguous':'grounded');
 return {...response,status,sources:response.sources??[],candidates:response.candidates??[]};
}
export const api={register:(body:RegisterRequest)=>apiRequest<SessionData>('/api/v1/auth/register',{method:'POST',body}),login:(body:LoginRequest)=>apiRequest<SessionData>('/api/v1/auth/login',{method:'POST',body}),logout:()=>apiRequest<void>('/api/v1/auth/logout',{method:'POST'}),session:()=>apiRequest<SessionData>('/api/v1/auth/session'),today:()=>apiRequest<Today>('/api/v1/today'),actions:(params:ActionListParams,signal?:AbortSignal)=>apiRequest<ActionList>(`/api/v1/actions${qs(params)}`,{signal,unwrapData:false}),notesHistory:(params:NotesHistoryParams,signal?:AbortSignal)=>apiRequest<NotesHistory>(`/api/v1/notes${qs(params)}`,{signal}),people:(params:PeopleListParams,signal?:AbortSignal)=>apiRequest<PeopleList>(`/api/v1/people${qs(params)}`,{signal}),tickets:(params:TicketsListParams,signal?:AbortSignal)=>apiRequest<TicketsList>(`/api/v1/tickets${qs(params)}`,{signal}),ticket:(key:string,signal?:AbortSignal)=>apiRequest<TicketWorkspaceDetail>(`/api/v1/tickets/${encodeURIComponent(key)}`,{signal}),person:(id:string,signal?:AbortSignal)=>apiRequest<PersonWorkspaceDetail>(`/api/v1/people/${encodeURIComponent(id)}`,{signal}),updatePerson:(id:string,body:UpdatePersonRequest,signal?:AbortSignal)=>apiRequest<UpdatePersonResponse>(`/api/v1/people/${encodeURIComponent(id)}`,{method:'PATCH',body,signal}),mergePerson:(primaryPersonId:string,body:PersonMergeRequest,signal?:AbortSignal)=>apiRequest<PersonMergeResponse>(`/api/v1/people/${encodeURIComponent(primaryPersonId)}/merge`,{method:'POST',body,signal}),createNote:(text:string)=>apiRequest<NoteCreated>('/api/v1/notes',{method:'POST',body:{text}}),note:(id:string)=>apiRequest<NoteDetail>(`/api/v1/notes/${encodeURIComponent(id)}`),updateAction:(id:string,status:ActionStatus)=>apiRequest<Action>(`/api/v1/actions/${encodeURIComponent(id)}`,{method:'PATCH',body:{status}}),ask:async(body:AskRequest,signal?:AbortSignal)=>normalizeAskResponse(await apiRequest<AskResponse>('/api/v1/ask',{method:'POST',body,signal})),summaries:(params:SummariesParams,signal?:AbortSignal)=>apiRequest<SummariesList>(`/api/v1/summaries${qs(params)}`,{signal}),summary:async(id:string,signal?:AbortSignal)=>unwrapSummaryResponse(await apiRequest<unknown>(`/api/v1/summaries/${encodeURIComponent(id)}`,{signal,unwrapData:false})),generateSummary:(body:SummaryGenerateRequest,signal?:AbortSignal)=>apiRequest<SummaryGenerateResult>('/api/v1/summaries/generate',{method:'POST',body,signal}),telegramStatus:(signal?:AbortSignal)=>apiRequest<TelegramStatus>('/api/v1/integrations/telegram/status',{signal}),telegramLink:()=>apiRequest<TelegramLink>('/api/v1/integrations/telegram/link',{method:'POST'}),telegramUnlink:()=>apiRequest<void>('/api/v1/integrations/telegram',{method:'DELETE'})};
