import { describe,it,expect,vi,beforeEach } from 'vitest';
import { api } from './endpoints';
import { ApiRequestError } from './client';
beforeEach(()=>{vi.restoreAllMocks()});
describe('person update endpoint',()=>{
 it('PATCHes the centralized person path and parses the data person envelope',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{id:'person_1',display_name:'Adlet',aliases:[],first_mentioned_at:'2026-03-12T10:00:00Z',last_mentioned_at:'2026-07-18T13:42:00Z',mention_count:14,updated_at:'2026-07-18T14:00:00Z'}}),{status:200,headers:{'Cache-Control':'no-store'}})) as typeof fetch;const updated=await api.updatePerson('person_1',{expected_updated_at:'old',first_name:null,aliases:[]});expect(fetch).toHaveBeenCalledWith('/api/backend/api/v1/people/person_1',expect.objectContaining({method:'PATCH',credentials:'include',body:JSON.stringify({expected_updated_at:'old',first_name:null,aliases:[]})}));expect(updated.display_name).toBe('Adlet');});
 it('serializes omitted aliases differently from explicit empty and populated arrays',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{id:'person_1',display_name:'Adlet',aliases:[],first_mentioned_at:'2026-03-12T10:00:00Z',last_mentioned_at:'2026-07-18T13:42:00Z',mention_count:14}}),{status:200})) as typeof fetch;await api.updatePerson('person_1',{display_name:'Adlet Updated'});await api.updatePerson('person_1',{aliases:[]});await api.updatePerson('person_1',{aliases:['A','B']});expect(vi.mocked(fetch).mock.calls[0][1]).toMatchObject({body:JSON.stringify({display_name:'Adlet Updated'})});expect(vi.mocked(fetch).mock.calls[1][1]).toMatchObject({body:JSON.stringify({aliases:[]})});expect(vi.mocked(fetch).mock.calls[2][1]).toMatchObject({body:JSON.stringify({aliases:['A','B']})});});
 it('propagates safe field errors without exposing raw bodies',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({error:{code:'validation_error',message:'raw',request_id:'req_1',fields:{display_name:'Required'}}}),{status:400})) as typeof fetch;await expect(api.updatePerson('person_1',{display_name:''})).rejects.toMatchObject({safe:{kind:'validation_error',fields:{display_name:'Required'}}});await expect(api.updatePerson('person_1',{display_name:''})).rejects.toBeInstanceOf(ApiRequestError);});
 it('maps 409 stale and identity conflicts to safe conflict errors',async()=>{global.fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({error:{code:'conflict',message:'raw',request_id:'req_1',fields:{expected_updated_at:'person_update_conflict'}}}),{status:409})).mockResolvedValueOnce(new Response(JSON.stringify({error:{code:'conflict',message:'raw',request_id:'req_2',fields:{aliases:'already used'}}}),{status:409})) as typeof fetch;await expect(api.updatePerson('person_1',{expected_updated_at:'old',display_name:'New'})).rejects.toMatchObject({safe:{kind:'conflict',fields:{expected_updated_at:'person_update_conflict'}}});await expect(api.updatePerson('person_1',{aliases:['Taken']})).rejects.toMatchObject({safe:{kind:'conflict',fields:{aliases:'already used'}}});});
});
