import { NextRequest } from 'next/server';

const HOP_BY_HOP_HEADERS=new Set(['connection','keep-alive','transfer-encoding','upgrade','proxy-authenticate','proxy-authorization','te','trailer']);
const UNSAFE_METHODS=new Set(['POST','PUT','PATCH','DELETE']);
const DEFAULT_TIMEOUT_MS=15000;
const ASK_TIMEOUT_MS=60000;
const SUMMARY_GENERATION_TIMEOUT_MS=105000;
const TIMEOUT_ENV={default:'BFF_DEFAULT_TIMEOUT',ask:'BFF_ASK_TIMEOUT',summaryGeneration:'BFF_SUMMARY_GENERATION_TIMEOUT'} as const;
const BACKEND_SUMMARY_TIMEOUT_ENV='BACKEND_SUMMARY_GENERATION_TIMEOUT';

export const runtime='nodejs';
export const maxDuration=120;

type RouteContext={params:Promise<{path?:string[]}>|{path?:string[]}};
type OriginValidationResult={response:Response|null;configuredOrigin:string|null;requestOrigin:string|null;originPresent:boolean;originMatched:boolean};
type TimeoutClass='default'|'ask'|'summary_generation';
type OperationTimeout={timeoutClass:TimeoutClass;timeoutMs:number};
type CombinedSignal={signal:AbortSignal;dispose:()=>void;timedOut:()=>boolean;clientAborted:()=>boolean};

function parseDurationMs(name:string,value:string|undefined,defaultMs:number){if(!value)return defaultMs;const trimmed=value.trim();const match=/^(\d+)(ms|s|m)?$/i.exec(trimmed);if(!match)throw new Error(`${name} must be a positive duration such as 15000ms, 15s, or 1m`);const amount=Number(match[1]);const unit=(match[2]??'ms').toLowerCase();const multiplier=unit==='m'?60000:unit==='s'?1000:1;const ms=amount*multiplier;if(!Number.isSafeInteger(ms)||ms<=0)throw new Error(`${name} must be a positive duration`);return ms;}
function getBackendBaseUrl(){const value=process.env.BACKEND_API_BASE_URL;if(!value)throw new Error('BACKEND_API_BASE_URL is required');return new URL(value.replace(/\/$/,''));}
function getFrontendOrigin(){const value=process.env.FRONTEND_ORIGIN;if(!value)throw new Error('FRONTEND_ORIGIN is required');return new URL(value).origin;}
function getTimeoutConfig(){const defaultTimeout=parseDurationMs(TIMEOUT_ENV.default,process.env[TIMEOUT_ENV.default],DEFAULT_TIMEOUT_MS);const askTimeout=parseDurationMs(TIMEOUT_ENV.ask,process.env[TIMEOUT_ENV.ask],ASK_TIMEOUT_MS);const summaryGenerationTimeout=parseDurationMs(TIMEOUT_ENV.summaryGeneration,process.env[TIMEOUT_ENV.summaryGeneration],SUMMARY_GENERATION_TIMEOUT_MS);const backendSummaryRaw=process.env[BACKEND_SUMMARY_TIMEOUT_ENV];if(backendSummaryRaw){const backendSummaryTimeout=parseDurationMs(BACKEND_SUMMARY_TIMEOUT_ENV,backendSummaryRaw,summaryGenerationTimeout);if(summaryGenerationTimeout<=backendSummaryTimeout)throw new Error(`${TIMEOUT_ENV.summaryGeneration} must be longer than ${BACKEND_SUMMARY_TIMEOUT_ENV}`)}return {defaultTimeout,askTimeout,summaryGenerationTimeout};}
function normalizeOrigin(value:string|null){if(!value)return null;try{return new URL(value).origin}catch{return null}}
function isSafeHeader(name:string){return !HOP_BY_HOP_HEADERS.has(name.toLowerCase());}
function logOriginValidation(operation:string,result:'accepted'|'rejected',originPresent:boolean,originMatched:boolean){console.info('frontend_proxy_origin_validation',{operation,result,origin_present:originPresent,origin_matched:originMatched});}
function logProxyEvent(fields:{route:string;method:string;timeoutClass:TimeoutClass;timeoutMs:number;durationMs:number;result:'success'|'timeout'|'client_aborted'|'unavailable';requestId:string}){console.info('frontend_proxy',{component:'frontend_proxy',operation:'proxy',route:fields.route,method:fields.method,timeout_class:fields.timeoutClass,configured_timeout_ms:fields.timeoutMs,duration_ms:fields.durationMs,result:fields.result,request_id:fields.requestId});}
function validateOrigin(req:NextRequest):OriginValidationResult{if(!UNSAFE_METHODS.has(req.method))return {response:null,configuredOrigin:null,requestOrigin:null,originPresent:false,originMatched:false};const configuredOrigin=getFrontendOrigin();const requestOrigin=normalizeOrigin(req.headers.get('origin'));const originPresent=req.headers.has('origin');const originMatched=requestOrigin===configuredOrigin;if(!originMatched){return {response:Response.json({error:{code:'forbidden',message:'Invalid request origin.',request_id:'frontend_proxy'}},{status:403}),configuredOrigin,requestOrigin,originPresent,originMatched}}return {response:null,configuredOrigin,requestOrigin,originPresent,originMatched};}
function buildTargetUrl(req:NextRequest,path:string[]){if(path.some(segment=>/^https?:$/i.test(segment)||segment.includes('://')))return null;const backend=getBackendBaseUrl();const target=new URL(backend.toString());target.pathname=`/${path.map(encodeURIComponent).join('/')}`;target.search=new URL(req.url).search;return target;}
function normalizedBackendPath(path:string[]){return `/${path.map(encodeURIComponent).join('/')}`;}
function timeoutFor(method:string,route:string):OperationTimeout{const config=getTimeoutConfig();if(method==='POST'&&route==='/api/v1/summaries/generate')return {timeoutClass:'summary_generation',timeoutMs:config.summaryGenerationTimeout};if(method==='POST'&&route==='/api/v1/ask')return {timeoutClass:'ask',timeoutMs:config.askTimeout};return {timeoutClass:'default',timeoutMs:config.defaultTimeout};}
function forwardedRequestHeaders(req:NextRequest,requestOrigin:string|null){const headers=new Headers();for(const name of ['content-type','accept','cookie','x-request-id','x-correlation-id','traceparent','tracestate']){const value=req.headers.get(name);if(value&&isSafeHeader(name))headers.set(name,value)}if(UNSAFE_METHODS.has(req.method)&&requestOrigin){headers.set('origin',requestOrigin)}return headers;}
function responseCookies(headers:Headers){const h=headers as Headers&{getSetCookie?:()=>string[]};const cookies=h.getSetCookie?.();if(cookies?.length)return cookies;const single=headers.get('set-cookie');return single?[single]:[];}
function rewriteSetCookie(cookie:string){const parts=cookie.split(';').map(part=>part.trim()).filter(Boolean);const first=parts.shift();if(!first)return cookie;let hasPath=false;let hasSameSite=false;const attrs:string[]=[];for(const part of parts){const [rawName]=part.split('=',1);const name=rawName.toLowerCase();if(name==='domain')continue;if(name==='path')hasPath=true;if(name==='samesite'){hasSameSite=true;attrs.push('SameSite=Lax');continue}attrs.push(part)}if(!hasPath)attrs.push('Path=/');if(!hasSameSite)attrs.push('SameSite=Lax');return [first,...attrs].join('; ');}
function forwardedResponseHeaders(backendHeaders:Headers){const headers=new Headers();for(const name of ['content-type','cache-control']){const value=backendHeaders.get(name);if(value)headers.set(name,value)}for(const cookie of responseCookies(backendHeaders)){headers.append('set-cookie',rewriteSetCookie(cookie))}return headers;}
function combinedTimeoutSignal(input:AbortSignal,timeoutMs:number):CombinedSignal{const controller=new AbortController();let timedOut=false;let clientAborted=input.aborted;const abortFromClient=()=>{clientAborted=true;controller.abort(input.reason)};const timeout=setTimeout(()=>{timedOut=true;controller.abort(new DOMException('BFF proxy request timed out','TimeoutError'))},timeoutMs);if(input.aborted)abortFromClient();else input.addEventListener('abort',abortFromClient,{once:true});return {signal:controller.signal,dispose:()=>{clearTimeout(timeout);input.removeEventListener('abort',abortFromClient)},timedOut:()=>timedOut,clientAborted:()=>clientAborted&&!timedOut};}
function errorName(e:unknown){return typeof e==='object'&&e&&'name' in e?String((e as {name?:unknown}).name):'';}
function safeTimeoutResponse(){return Response.json({error:{code:'timeout',message:'Lead Log backend request timed out.',request_id:'frontend_proxy'}},{status:504,headers:{'cache-control':'no-store'}});}
function safeUnavailableResponse(){return Response.json({error:{code:'service_unavailable',message:'Lead Log backend is temporarily unavailable.',request_id:'frontend_proxy'}},{status:503,headers:{'cache-control':'no-store'}});}

export async function proxyBackend(req:NextRequest,context:RouteContext){const started=Date.now();const params=await context.params;const path=params.path??[];const route=normalizedBackendPath(path);const requestId=req.headers.get('x-request-id')??req.headers.get('x-correlation-id')??'frontend_proxy';const originValidation=validateOrigin(req);if(originValidation.response){logOriginValidation(`${req.method} /api/backend`,'rejected',originValidation.originPresent,originValidation.originMatched);return originValidation.response}if(UNSAFE_METHODS.has(req.method)){logOriginValidation(`${req.method} /api/backend`,'accepted',originValidation.originPresent,originValidation.originMatched)}const target=buildTargetUrl(req,path);if(!target)return Response.json({error:{code:'not_found',message:'Unknown backend path.',request_id:'frontend_proxy'}},{status:404});const operationTimeout=timeoutFor(req.method,route);const combined=combinedTimeoutSignal(req.signal,operationTimeout.timeoutMs);
 const init:RequestInit={method:req.method,headers:forwardedRequestHeaders(req,originValidation.requestOrigin),redirect:'manual',signal:combined.signal};if(req.method!=='GET'&&req.method!=='HEAD')init.body=await req.arrayBuffer();
 let backendRes:Response;try{backendRes=await fetch(target,init)}catch(e){const durationMs=Date.now()-started;const name=errorName(e);if(combined.timedOut()||name==='TimeoutError'){logProxyEvent({route,method:req.method,timeoutClass:operationTimeout.timeoutClass,timeoutMs:operationTimeout.timeoutMs,durationMs,result:'timeout',requestId});combined.dispose();return safeTimeoutResponse()}if(combined.clientAborted()||req.signal.aborted){logProxyEvent({route,method:req.method,timeoutClass:operationTimeout.timeoutClass,timeoutMs:operationTimeout.timeoutMs,durationMs,result:'client_aborted',requestId});combined.dispose();return new Response(null,{status:499})}logProxyEvent({route,method:req.method,timeoutClass:operationTimeout.timeoutClass,timeoutMs:operationTimeout.timeoutMs,durationMs,result:'unavailable',requestId});combined.dispose();return safeUnavailableResponse()}
 combined.dispose();logProxyEvent({route,method:req.method,timeoutClass:operationTimeout.timeoutClass,timeoutMs:operationTimeout.timeoutMs,durationMs:Date.now()-started,result:'success',requestId});return new Response(backendRes.body,{status:backendRes.status,headers:forwardedResponseHeaders(backendRes.headers)});
}
export const GET=proxyBackend;export const POST=proxyBackend;export const PUT=proxyBackend;export const PATCH=proxyBackend;export const DELETE=proxyBackend;
