import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,it,expect,vi,beforeEach } from 'vitest';
import { AskPage } from './ask-page';
import { api } from '@/lib/api/endpoints';
import { ApiRequestError } from '@/lib/api/client';
import type { NoteDetail } from '@/lib/api/types';
vi.mock('next/link',()=>({default:({href,children,className}:{href:string;children:React.ReactNode;className?:string})=><a href={href} className={className}>{children}</a>}));
vi.mock('@/lib/api/endpoints',()=>({api:{ask:vi.fn(),note:vi.fn()}}));
const note:NoteDetail={id:'note_1',raw_text:'Raw note',summary:'Summary',processing_status:'processed',created_at:'2026-07-18T13:42:00Z',processed_at:null,actions:[],people:[],decisions:[],entities:[]};
beforeEach(()=>{vi.mocked(api.ask).mockReset();vi.mocked(api.note).mockReset();vi.mocked(api.note).mockResolvedValue(note);});
describe('AskPage',()=>{
 it('renders initial composer and suggestions without requesting on mount',()=>{render(<AskPage/>);expect(screen.getByRole('heading',{level:1,name:'Ask Lead Log'})).toBeInTheDocument();expect(screen.getByLabelText('Ask about your work')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Ask Lead Log'})).toBeDisabled();expect(screen.getByRole('button',{name:'What did I do yesterday?'})).toBeInTheDocument();expect(api.ask).not.toHaveBeenCalled();});
 it('populates suggestions, submits one trimmed multiline question, and preserves paragraphs and metadata',async()=>{vi.mocked(api.ask).mockResolvedValue({status:'grounded',answer:'First paragraph.\n\nSecond <script>alert(1)</script>.',sources:[{type:'note',label:'Retry discussion',timestamp:'2026-07-18T13:42:00Z',excerpt:'Discussed retry policy.',note_id:'note_1'},{type:'person',label:'A person',person_id:'person_1'},{type:'ticket',label:'CH-1234',ticket_key:'CH-1234'},{type:'action',label:'Follow up'},{type:'decision',label:'Decision',source_note_id:'note_1'},{type:'weekly_summary',label:'Weekly summary'}],scope:{label:'July 13–19, 2026'},confidence:'grounded'});render(<AskPage/>);await userEvent.click(screen.getByRole('button',{name:'What did I do yesterday?'}));const box=screen.getByLabelText('Ask about your work');expect(box).toHaveValue('What did I do yesterday?');await userEvent.clear(box);await userEvent.type(box,'  Line one{Shift>}{Enter}{/Shift}Line two  ');await userEvent.click(screen.getByRole('button',{name:'Ask Lead Log'}));await screen.findByRole('heading',{level:2,name:'Answer'});expect(api.ask).toHaveBeenCalledTimes(1);expect(api.ask).toHaveBeenCalledWith({question:'Line one\nLine two'},expect.any(AbortSignal));expect(screen.getByText(/First paragraph/)).toHaveTextContent('Second <script>alert(1)</script>.');expect(document.querySelector('script')).toBeNull();expect(screen.getByText('grounded')).toBeInTheDocument();expect(screen.getByText(/Scope: July 13–19, 2026/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open person'})).toHaveAttribute('href','/people/person_1');expect(screen.getByRole('link',{name:'Open ticket'})).toHaveAttribute('href','/tickets/CH-1234');expect(screen.getByRole('link',{name:'Open actions'})).toHaveAttribute('href','/actions');expect(screen.getByText('Evidence only')).toBeInTheDocument();expect(screen.queryByText('person_1')).not.toBeInTheDocument();});
 it('opens note detail once without refetching ask and preserves answer on close',async()=>{vi.mocked(api.ask).mockResolvedValue({status:'grounded',answer:'Answer',sources:[{type:'note',label:'Note',note_id:'note_1'}]});render(<AskPage/>);await userEvent.type(screen.getByLabelText('Ask about your work'),'Question');await userEvent.click(screen.getByRole('button',{name:'Ask Lead Log'}));await screen.findByRole('heading',{level:2,name:'Answer'});await userEvent.click(screen.getByRole('button',{name:'Open note'}));await screen.findByRole('heading',{level:3,name:'Raw note'});expect(api.note).toHaveBeenCalledTimes(1);expect(api.ask).toHaveBeenCalledTimes(1);await userEvent.click(screen.getByRole('button',{name:'Close details'}));expect(screen.getByText('Answer',{selector:'p'})).toBeInTheDocument();});
 it('renders insufficient context, ambiguity, retryable errors, and validation errors distinctly',async()=>{vi.mocked(api.ask).mockResolvedValueOnce({status:'insufficient_context',message:'Not enough.',sources:[],confidence:'insufficient'}).mockResolvedValueOnce({status:'ambiguous',message:'I found multiple people named Alex. Please include more context.',sources:[],confidence:'ambiguous'}).mockRejectedValueOnce(new ApiRequestError({kind:'service_unavailable',status:503,message:'no'})).mockResolvedValueOnce({status:'grounded',answer:'Retried',sources:[]}).mockRejectedValueOnce(new ApiRequestError({kind:'validation_error',status:400,message:'bad'}));render(<AskPage/>);const box=screen.getByLabelText('Ask about your work');await userEvent.type(box,'Unknown');await userEvent.click(screen.getByRole('button',{name:'Ask Lead Log'}));await screen.findByText(/could not find enough information/);await userEvent.clear(box);await userEvent.type(box,'Alex');await userEvent.click(screen.getByRole('button',{name:'Ask Lead Log'}));await screen.findByText(/multiple people named Alex/);await userEvent.clear(box);await userEvent.type(box,'Provider');await userEvent.click(screen.getByRole('button',{name:'Ask Lead Log'}));await screen.findByText('Lead Log is temporarily unable to answer. Try again.');await userEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByText('Retried');await userEvent.clear(box);await userEvent.type(box,'Bad');await userEvent.click(screen.getByRole('button',{name:'Ask Lead Log'}));await waitFor(()=>expect(screen.getAllByText('Check the question and try again.').length).toBeGreaterThan(0));});
 it('blocks duplicate and stale submissions, supports cancel, and does not persist content',async()=>{let resolveFirst:(v:any)=>void=()=>{};vi.mocked(api.ask).mockImplementationOnce((_b,signal)=>new Promise((resolve,reject)=>{resolveFirst=resolve;signal?.addEventListener('abort',()=>reject(Object.assign(new Error('Abort'),{name:'AbortError'})));})).mockResolvedValueOnce({status:'grounded',answer:'Second',sources:[]});render(<AskPage/>);const box=screen.getByLabelText('Ask about your work');await userEvent.type(box,'First');const submit=screen.getByRole('button',{name:'Ask Lead Log'});await userEvent.click(submit);await userEvent.click(submit);expect(api.ask).toHaveBeenCalledTimes(1);await userEvent.click(screen.getByRole('button',{name:'Cancel'}));await waitFor(()=>expect(screen.queryByText(/Unable to answer/)).not.toBeInTheDocument());await userEvent.clear(box);await userEvent.type(box,'Second');await userEvent.click(screen.getByRole('button',{name:'Ask Lead Log'}));resolveFirst({status:'grounded',answer:'Stale',sources:[]});await screen.findByRole('heading',{level:2,name:'Answer'});expect(screen.getAllByText('Second',{selector:'p'}).length).toBeGreaterThan(0);expect(screen.queryByText('Stale')).not.toBeInTheDocument();expect(window.localStorage.length).toBe(0);expect(window.sessionStorage.length).toBe(0);});
});
