'use client';
import Link from 'next/link';
import { usePathname,useRouter,useSearchParams } from 'next/navigation';
import { FormEvent,useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { ApiRequestError } from '@/lib/api/client';
import { api } from '@/lib/api/endpoints';
import type { SafeApiError,TicketListItem,TicketsListParams } from '@/lib/api/types';
import { formatDateTime } from '@/lib/formatting/date';
const LIMIT=20;const QUERY_MIN=2;const QUERY_MAX=100;
type Filters={query:string;has_open_actions:boolean};const emptyFilters:Filters={query:'',has_open_actions:false};
function normalize(sp:URLSearchParams):Filters{const q=(sp.get('query')??'').trim().slice(0,QUERY_MAX);return{query:q.length===1?'':q,has_open_actions:sp.get('has_open_actions')==='true'}}
function hasFilters(f:Filters){return !!(f.query||f.has_open_actions)}
function buildQuery(f:Filters){const sp=new URLSearchParams();if(f.query)sp.set('query',f.query);if(f.has_open_actions)sp.set('has_open_actions','true');const q=sp.toString();return q?`?${q}`:''}
function params(f:Filters,cursor?:string):TicketsListParams{return{limit:LIMIT,cursor,query:f.query||undefined,has_open_actions:f.has_open_actions||undefined}}
function safeError(e:unknown):SafeApiError{return e instanceof ApiRequestError?e.safe:{kind:'unexpected_error',message:'Something went wrong. Try again.'}}
function plural(n:number,label:string){return `${n} ${label}${n===1?'':'s'}`}
function cap(s:string,n=220){return s.length>n?`${s.slice(0,n)}…`:s}
function ActiveFilters({filters,onClear,onClearAll}:{filters:Filters;onClear:(k:keyof Filters)=>void;onClearAll:()=>void}){if(!hasFilters(filters))return null;return <div className="filter-chips" aria-label="Active filters">{filters.query&&<button className="chip filter-chip" onClick={()=>onClear('query')} aria-label="Remove Search filter">Search: {filters.query} ×</button>}{filters.has_open_actions&&<button className="chip filter-chip" onClick={()=>onClear('has_open_actions')} aria-label="Remove open actions filter">Has open actions ×</button>}<button className="btn" onClick={onClearAll}>Clear all</button></div>}
function TicketCard({ticket}:{ticket:TicketListItem}){return <Link className="card person-card ticket-card" href={`/tickets/${encodeURIComponent(ticket.key)}`}><div className="action-row person-card-head"><strong className="ticket-key">{ticket.key}</strong><span className="chip">{plural(ticket.mention_count,'mention')}</span></div><p className="muted"><span className="chip">First mentioned: {formatDateTime(ticket.first_mentioned_at)}</span> <span className="chip">Last mentioned: {formatDateTime(ticket.last_mentioned_at)}</span> {ticket.open_action_count>0?<span className="chip">{plural(ticket.open_action_count,'open action')}</span>:<span className="chip">0 open actions</span>}</p>{ticket.recent_note?<div className="recent-note"><p>{ticket.recent_note.summary?cap(ticket.recent_note.summary):'Recent note has no summary yet.'}</p><p className="muted">Recent note: {formatDateTime(ticket.recent_note.created_at)}</p></div>:<p className="muted">No recent note preview available.</p>}</Link>}
export function TicketsPage(){const router=useRouter();const pathname=usePathname();const searchParams=useSearchParams();const filters=useMemo(()=>normalize(searchParams),[searchParams]);const[draft,setDraft]=useState(filters.query);const[tickets,setTickets]=useState<TicketListItem[]>([]);const[next,setNext]=useState<string|null>(null);const[hasMore,setHasMore]=useState(false);const[loading,setLoading]=useState(true);const[moreLoading,setMoreLoading]=useState(false);const[error,setError]=useState<SafeApiError|null>(null);const[moreError,setMoreError]=useState<SafeApiError|null>(null);const req=useRef(0);const moreRef=useRef(false);
useEffect(()=>setDraft(filters.query),[filters.query]);
const replaceFilters=useCallback((f:Filters,push=false)=>{const url=`${pathname}${buildQuery(f)}`;(push?router.push:router.replace)(url,{scroll:false})},[pathname,router]);
useEffect(()=>{if(buildQuery(filters)!==`?${searchParams.toString()}`&&searchParams.toString())router.replace(`${pathname}${buildQuery(filters)}`,{scroll:false})},[filters,pathname,router,searchParams]);
const loadFirst=useCallback(async(signal?:AbortSignal)=>{const active={query:filters.query,has_open_actions:filters.has_open_actions};const id=++req.current;setLoading(true);setError(null);setMoreError(null);try{const data=await api.tickets(params(active),signal);if(id!==req.current)return;const seen=new Set<string>();setTickets(data.items.filter(t=>!seen.has(t.key)&&!!seen.add(t.key)));setNext(data.page.next_cursor);setHasMore(data.page.has_more&&!!data.page.next_cursor)}catch(e){if(signal?.aborted||id!==req.current)return;setTickets([]);setNext(null);setHasMore(false);setError(safeError(e))}finally{if(id===req.current)setLoading(false)}},[filters.query,filters.has_open_actions]);
useEffect(()=>{const ac=new AbortController();void loadFirst(ac.signal);return()=>ac.abort()},[loadFirst]);
useEffect(()=>{if(draft===filters.query)return;const id=window.setTimeout(()=>{const q=draft.trim().slice(0,QUERY_MAX);if(q.length>0&&q.length<QUERY_MIN)return;replaceFilters({...filters,query:q},false)},400);return()=>window.clearTimeout(id)},[draft,filters,replaceFilters]);
async function loadMore(){if(!next||moreRef.current)return;moreRef.current=true;const id=req.current;setMoreLoading(true);setMoreError(null);try{const data=await api.tickets(params(filters,next));if(id!==req.current)return;setTickets(prev=>{const seen=new Set(prev.map(t=>t.key));return[...prev,...data.items.filter(t=>!seen.has(t.key)&&!!seen.add(t.key))]});setNext(data.page.next_cursor);setHasMore(data.page.has_more&&!!data.page.next_cursor)}catch(e){if(id===req.current)setMoreError(safeError(e))}finally{if(id===req.current)setMoreLoading(false);moreRef.current=false}}
function submit(e:FormEvent){e.preventDefault();const q=draft.trim().slice(0,QUERY_MAX);if(q.length>0&&q.length<QUERY_MIN)return;replaceFilters({...filters,query:q},true)}
function change(k:keyof Filters,v:string|boolean){replaceFilters({...filters,[k]:v},true)}
const filtered=hasFilters(filters);return <div className="stack people-page tickets-page"><header><p className="chip">Tickets</p><h1>Tickets</h1><p className="muted">Browse ticket keys extracted from your notes, newest mentions first.</p></header><form className="card section people-filters" onSubmit={submit}><label className="field search-field"><strong>Search tickets</strong><span className="search-row"><input value={draft} onChange={e=>setDraft(e.target.value.slice(0,QUERY_MAX))} maxLength={QUERY_MAX} placeholder="Search by ticket key" />{draft&&<button type="button" className="btn" onClick={()=>{setDraft('');replaceFilters({...filters,query:''},true)}}>Clear</button>}</span>{draft.trim().length===1&&<span className="error">Search needs at least 2 characters.</span>}</label><label className="open-filter"><input type="checkbox" checked={filters.has_open_actions} onChange={e=>change('has_open_actions',e.target.checked)}/> Only tickets with open actions</label><button className="btn primary" type="submit">Apply</button></form><ActiveFilters filters={filters} onClear={k=>change(k,k==='has_open_actions'?false:'')} onClearAll={()=>replaceFilters(emptyFilters,true)}/><p className="muted" aria-live="polite">{loading?'Loading tickets…':`${tickets.length} ${tickets.length===1?'ticket':'tickets'} loaded${hasMore?' · more tickets available':''}`}</p><section className="stack" aria-label="Ticket directory">{loading&&<div className="card section skeleton" role="status">Loading tickets…</div>}{error&&!loading&&<div className="card section" role="alert"><p className="error">{error.kind==='validation_error'?'These filters are invalid. Adjust them and try again.':error.message}</p><button className="btn" onClick={()=>loadFirst()}>Retry</button></div>}{!loading&&!error&&tickets.length===0&&<div className="card section"><h2>{filtered?'No tickets match these filters':'No tickets found yet'}</h2><p className="muted">{filtered?'Try changing the search or open-actions filter.':'Tickets will appear after Lead Log extracts them from your notes.'}</p>{filtered?<button className="btn" onClick={()=>replaceFilters(emptyFilters,true)}>Clear filters</button>:<p className="action-row empty-actions"><Link className="btn" href="/today">Go to Today</Link><Link className="btn" href="/notes">Browse Notes</Link></p>}</div>}{!loading&&!error&&tickets.map(t=><TicketCard key={t.key} ticket={t}/>) }{moreError&&<div className="card section" role="alert"><p className="error">Could not load more tickets. {moreError.message}</p><button className="btn" onClick={loadMore}>Retry</button></div>}{!loading&&!error&&hasMore&&<button className="btn" onClick={loadMore} disabled={moreLoading} aria-busy={moreLoading}>{moreLoading?'Loading more tickets…':'Load more tickets'}</button>}</section></div>}
