'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ActionSection } from '@/components/actions/action-section';
import { NoteDetailPanel } from '@/components/today/note-detail-panel';
import { StatusChip } from '@/components/today/status';
import { ApiRequestError } from '@/lib/api/client';
import { api } from '@/lib/api/endpoints';
import type { Action,SafeApiError,TicketWorkspaceDetail } from '@/lib/api/types';
import { formatDateTime } from '@/lib/formatting/date';
function safeError(e:unknown):SafeApiError{return e instanceof ApiRequestError?e.safe:{kind:'unexpected_error',message:'Something went wrong. Try again.'}}
function plural(n:number,label:string){return `${n} ${label}${n===1?'':'s'}`}
function cap(s:string,n=260){return s.length>n?`${s.slice(0,n)}…`:s}
export function TicketDetailPage({ticketKey}:{ticketKey:string}){const router=useRouter();const routerRef=useRef(router);routerRef.current=router;const[data,setData]=useState<TicketWorkspaceDetail|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<SafeApiError|null>(null);const[selected,setSelected]=useState<string|null>(null);const req=useRef(0);const replaced=useRef(false);const decoded=decodeURIComponent(ticketKey);
const load=useCallback(async(signal?:AbortSignal)=>{const id=++req.current;setLoading(true);setError(null);try{const d=await api.ticket(decoded,signal);if(id!==req.current)return;setData(d);if(!replaced.current&&d.ticket.key!==decoded){replaced.current=true;routerRef.current.replace(`/tickets/${encodeURIComponent(d.ticket.key)}`,{scroll:false})}}catch(e){if(signal?.aborted||id!==req.current)return;setError(safeError(e));setData(null)}finally{if(id===req.current)setLoading(false)}},[decoded]);
useEffect(()=>{const ac=new AbortController();void load(ac.signal);return()=>ac.abort()},[load]);
function updateAction(updated:Action){setData(prev=>prev?{...prev,open_actions:updated.status==='open'?prev.open_actions.map(a=>a.id===updated.id?updated:a):prev.open_actions.filter(a=>a.id!==updated.id)}:prev)}
if(loading)return <div className="stack"><Link className="btn back-link" href="/tickets">Back to Tickets</Link><div className="card section skeleton" role="status">Loading ticket…</div></div>;
if(error){const title=error.kind==='not_found'?'Ticket not found':error.kind==='validation_error'?'Invalid ticket key':'Ticket unavailable';return <div className="stack"><Link className="btn back-link" href="/tickets">Back to Tickets</Link><div className="card section" role="alert"><h1>{title}</h1><p className="muted">{error.kind==='not_found'?'This ticket is not available in your workspace.':error.kind==='validation_error'?'This ticket key cannot be opened.':error.message}</p>{error.kind!=='not_found'&&error.kind!=='validation_error'&&<button className="btn" onClick={()=>load()}>Retry</button>}</div></div>}
if(!data)return null;const t=data.ticket;return <div className="stack person-detail-page ticket-detail-page"><Link className="btn back-link" href="/tickets">Back to Tickets</Link><header className="card section stack person-header"><p className="chip">Ticket profile</p><h1>{t.key}</h1><p className="muted"><span className="chip">First mentioned: {formatDateTime(t.first_mentioned_at)}</span> <span className="chip">Last mentioned: {formatDateTime(t.last_mentioned_at)}</span> <span className="chip">{plural(t.mention_count,'mention')}</span></p></header><div className="today-grid notes-grid"><div className="stack"><ActionSection actions={data.open_actions} emptyText="No open actions linked to this ticket." onUpdate={updateAction}/><section className="card section stack"><h2>Recent decisions</h2>{data.recent_decisions.length?data.recent_decisions.map(d=><article key={d.id} className="decision-item"><p>{d.text}</p><p className="muted"><span className="chip">Status: {d.status}</span>{d.topic&&<span className="chip">Topic: {d.topic}</span>}</p></article>):<p className="muted">No recent decisions linked to this ticket.</p>}</section><section className="card section stack"><h2>Recent notes</h2>{data.recent_notes.length?data.recent_notes.map(n=><button key={n.id} className="note-card history-note" onClick={()=>setSelected(n.id)} aria-label={`Open source note from ${formatDateTime(n.created_at)}`}><div className="action-row"><strong>{n.summary?cap(n.summary,120):'No summary available.'}</strong>{n.processing_status&&n.processing_status!=='processed'&&<StatusChip status={n.processing_status}/>}</div>{n.raw_text_preview&&<p className="muted raw-preview">{cap(n.raw_text_preview)}</p>}<p className="muted"><span className="chip">{formatDateTime(n.created_at)}</span>{n.people?.map(p=><span className="chip" key={p.id}>{p.display_name}</span>)}</p></button>):<p className="muted">No recent notes linked to this ticket.</p>}</section></div><NoteDetailPanel noteId={selected} onClose={()=>setSelected(null)} onFinished={()=>{}}/></div></div>}
