import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,it,expect,vi,beforeEach } from 'vitest';
import { TicketDetailPage } from './ticket-detail-page';
import { api } from '@/lib/api/endpoints';
import { ApiRequestError } from '@/lib/api/client';
import type { NoteDetail,TicketWorkspaceDetail } from '@/lib/api/types';
const replace=vi.fn();
vi.mock('next/navigation',()=>({useRouter:()=>({replace})}));
vi.mock('@/lib/api/endpoints',()=>({api:{ticket:vi.fn(),updateAction:vi.fn(),note:vi.fn()}}));
const detail=():TicketWorkspaceDetail=>({ticket:{key:'CH-1234',first_mentioned_at:'2026-05-03T10:15:00Z',last_mentioned_at:'2026-07-19T14:25:00Z',mention_count:9},open_actions:[{id:'action_1',title:'Follow up on retry policy',status:'open',linked_person:{display_name:'Adlet'},due_at:'2026-07-17T09:00:00Z',created_at:'2026-07-16T09:00:00Z',completed_at:null,source_note_id:'note_1'}],recent_decisions:[{id:'decision_1',text:'Use bounded retries.',status:'active',topic:'Retry policy'}],recent_notes:[{id:'note_1',created_at:'2026-07-19T14:25:00Z',summary:'Reviewed retry policy.',raw_text_preview:'Raw preview',processing_status:'processed',people:[{id:'person_1',display_name:'Adlet'}]}],page:{next_cursor:null,has_more:false}});
const note:NoteDetail={id:'note_1',raw_text:'Raw note',summary:'Full summary',processing_status:'processed',created_at:'2026-07-19T14:25:00Z',processed_at:null,actions:[],people:[],decisions:[],entities:[]};
beforeEach(()=>{replace.mockClear();vi.mocked(api.ticket).mockReset();vi.mocked(api.updateAction).mockReset();vi.mocked(api.note).mockReset();vi.mocked(api.note).mockResolvedValue(note);});
describe('TicketDetailPage',()=>{
 it('renders ticket metadata, actions, decisions, recent notes, and shared note detail',async()=>{vi.mocked(api.ticket).mockResolvedValue(detail());render(<TicketDetailPage ticketKey="CH-1234"/>);expect(screen.getByRole('status')).toHaveTextContent('Loading ticket');await screen.findByRole('heading',{level:1,name:'CH-1234'});expect(screen.getByText(/First mentioned:/)).toBeInTheDocument();expect(screen.getByText(/Last mentioned:/)).toBeInTheDocument();expect(screen.getByText('9 mentions')).toBeInTheDocument();expect(screen.getByText('Follow up on retry policy')).toBeInTheDocument();expect(screen.getByText('Use bounded retries.')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:/Open source note/}));await screen.findByText('Full summary');expect(api.ticket).toHaveBeenCalledTimes(1);expect(api.note).toHaveBeenCalledTimes(1);await userEvent.click(screen.getByRole('button',{name:'Close details'}));expect(screen.getByRole('heading',{level:1,name:'CH-1234'})).toBeInTheDocument();});
 it('completes an action locally and keeps unrelated sections on failure',async()=>{vi.mocked(api.ticket).mockResolvedValue(detail());vi.mocked(api.updateAction).mockResolvedValueOnce({...detail().open_actions[0],status:'done',completed_at:'2026-07-19T15:00:00Z'});render(<TicketDetailPage ticketKey="CH-1234"/>);await screen.findByText('Follow up on retry policy');await userEvent.click(screen.getByRole('button',{name:/Complete action/}));await waitFor(()=>expect(screen.queryByText('Follow up on retry policy')).not.toBeInTheDocument());expect(screen.getByText('Use bounded retries.')).toBeInTheDocument();vi.mocked(api.updateAction).mockRejectedValueOnce(new Error('nope'));});
 it('handles empty sections, invalid keys, not found, retryable errors, and canonical replacement',async()=>{vi.mocked(api.ticket).mockResolvedValue({...detail(),open_actions:[],recent_decisions:[],recent_notes:[]});const {rerender}=render(<TicketDetailPage ticketKey="CH-1234"/>);await screen.findByText('No open actions linked to this ticket.');expect(screen.getByText('No recent decisions linked to this ticket.')).toBeInTheDocument();expect(screen.getByText('No recent notes linked to this ticket.')).toBeInTheDocument();vi.mocked(api.ticket).mockRejectedValue(new ApiRequestError({kind:'validation_error',status:400,message:'bad'}));rerender(<TicketDetailPage ticketKey="bad key"/>);await screen.findByRole('heading',{level:1,name:'Invalid ticket key'});vi.mocked(api.ticket).mockRejectedValue(new ApiRequestError({kind:'not_found',status:404,message:'missing'}));rerender(<TicketDetailPage ticketKey="NOPE-1"/>);await screen.findByRole('heading',{level:1,name:'Ticket not found'});vi.mocked(api.ticket).mockRejectedValueOnce(new Error('network')).mockResolvedValueOnce(detail());rerender(<TicketDetailPage ticketKey="ERR-1"/>);await screen.findByRole('button',{name:'Retry'});await userEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByRole('heading',{level:1,name:'CH-1234'});vi.mocked(api.ticket).mockResolvedValueOnce(detail());rerender(<TicketDetailPage ticketKey="ch-1234"/>);await waitFor(()=>expect(replace).toHaveBeenCalledWith('/tickets/CH-1234',{scroll:false}));});
});
