import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,it,expect,vi,beforeEach } from 'vitest';
import { TicketsPage } from './tickets-page';
import { api } from '@/lib/api/endpoints';
import type { TicketsList } from '@/lib/api/types';
let query='';const replace=vi.fn((url:string)=>{query=url.split('?')[1]??''});const push=vi.fn((url:string)=>{query=url.split('?')[1]??''});
vi.mock('next/navigation',()=>({useRouter:()=>({replace,push}),usePathname:()=>'/tickets',useSearchParams:()=>new URLSearchParams(query)}));
vi.mock('@/lib/api/endpoints',()=>({api:{tickets:vi.fn()}}));
const ticket=(key:string)=>({key,first_mentioned_at:'2026-05-03T10:15:00Z',last_mentioned_at:'2026-07-19T14:25:00Z',mention_count:9,open_action_count:2,recent_note:{id:'note_184',created_at:'2026-07-19T14:25:00Z',summary:'Reviewed retry-policy implementation.'}});
const page=(items:any[],next_cursor:string|null=null):TicketsList=>({items,page:{next_cursor,has_more:!!next_cursor}});
beforeEach(()=>{query='';replace.mockClear();push.mockClear();vi.mocked(api.tickets).mockReset();});
describe('TicketsPage',()=>{
 it('shows skeleton, makes one initial request, and renders ticket cards without per-card calls',async()=>{vi.mocked(api.tickets).mockResolvedValue(page([ticket('CH-1234')],'cursor_2'));const {rerender}=render(<TicketsPage/>);expect(screen.getByRole('heading',{level:1,name:'Tickets'})).toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('Loading tickets');await screen.findByText('CH-1234');expect(api.tickets).toHaveBeenCalledTimes(1);expect(api.tickets).toHaveBeenLastCalledWith({limit:20,cursor:undefined,query:undefined,has_open_actions:undefined},expect.any(AbortSignal));expect(screen.getByText('9 mentions')).toBeInTheDocument();expect(screen.getByText(/Last mentioned:/)).toBeInTheDocument();expect(screen.getByText('2 open actions')).toBeInTheDocument();expect(screen.getByText('Reviewed retry-policy implementation.')).toBeInTheDocument();expect(screen.getByRole('link',{name:/CH-1234/})).toHaveAttribute('href','/tickets/CH-1234');rerender(<TicketsPage/>);expect(api.tickets).toHaveBeenCalledTimes(1);});
 it('initializes URL filters, debounces search, toggles open-actions, and clears without logging',async()=>{query='query=CH-1234&has_open_actions=true';vi.mocked(api.tickets).mockResolvedValue(page([ticket('CH-1234')]));render(<TicketsPage/>);await waitFor(()=>expect(api.tickets).toHaveBeenCalled());expect(api.tickets).toHaveBeenLastCalledWith(expect.objectContaining({query:'CH-1234',has_open_actions:true}),expect.any(AbortSignal));expect(screen.getByDisplayValue('CH-1234')).toBeInTheDocument();expect(screen.getByLabelText('Only tickets with open actions')).toBeChecked();await userEvent.type(screen.getByLabelText('Search tickets'),'x');await waitFor(()=>expect(replace).toHaveBeenCalledWith('/tickets?query=CH-1234x&has_open_actions=true',{scroll:false}),{timeout:800});await userEvent.click(screen.getByLabelText('Remove open actions filter'));expect(push).toHaveBeenCalledWith('/tickets?query=CH-1234',{scroll:false});await userEvent.click(screen.getByRole('button',{name:'Clear'}));expect(push).toHaveBeenCalledWith('/tickets?has_open_actions=true',{scroll:false});});
 it('paginates with opaque cursor, appends in order, deduplicates, and blocks duplicate clicks',async()=>{vi.mocked(api.tickets).mockResolvedValueOnce(page([ticket('CH-1234')],'cursor_2')).mockImplementationOnce(()=>new Promise(r=>setTimeout(()=>r(page([ticket('ABC-7'),ticket('CH-1234')],null)),20)) as any);render(<TicketsPage/>);await screen.findByText('CH-1234');await userEvent.dblClick(screen.getByRole('button',{name:'Load more tickets'}));expect(api.tickets).toHaveBeenCalledTimes(2);await screen.findByText('ABC-7');expect(screen.getAllByText('CH-1234')).toHaveLength(1);expect(api.tickets).toHaveBeenLastCalledWith(expect.objectContaining({cursor:'cursor_2'}));});
 it('shows contextual empty and error states and retries initial failures',async()=>{vi.mocked(api.tickets).mockRejectedValueOnce(new Error('network'));const {rerender}=render(<TicketsPage/>);await screen.findByRole('alert');expect(screen.getByText(/Something went wrong/)).toBeInTheDocument();vi.mocked(api.tickets).mockResolvedValue(page([]));await userEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByText('No tickets found yet');query='query=ZZ';rerender(<TicketsPage/>);await screen.findByText('No tickets match these filters');});
});
