import { describe,it,expect,vi,beforeEach,afterEach } from 'vitest';
import { NextRequest } from 'next/server';
import { proxyBackend } from './[...path]/route';

function req(path:string,init:RequestInit={}){return new NextRequest(`https://lead-log-fe-production.up.railway.app${path}`,init)}
function ctx(path:string[]){return {params:{path}}}
async function call(path:string[],requestPath:string,init:RequestInit={}){return proxyBackend(req(requestPath,init),ctx(path))}

beforeEach(()=>{vi.stubEnv('BACKEND_API_BASE_URL','https://lead-log-production.up.railway.app');vi.stubEnv('FRONTEND_ORIGIN','https://lead-log-fe-production.up.railway.app');vi.spyOn(console,'log').mockImplementation(()=>{});vi.spyOn(console,'error').mockImplementation(()=>{});vi.spyOn(console,'warn').mockImplementation(()=>{});vi.spyOn(console,'info').mockImplementation(()=>{})});
afterEach(()=>{vi.unstubAllEnvs();vi.restoreAllMocks()});

describe('backend BFF proxy',()=>{
 it('forwards login Set-Cookie for frontend origin without Domain',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{ok:true}}),{status:200,headers:{'content-type':'application/json','set-cookie':'lead_log_session=abc; Domain=lead-log-production.up.railway.app; HttpOnly; Secure; Path=/; SameSite=None'}})) as typeof fetch;const res=await call(['api','v1','auth','login'],'/api/backend/api/v1/auth/login',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app','content-type':'application/json'},body:'{"email":"a@b.com","password":"secretsecret"}'});expect(res.status).toBe(200);expect(res.headers.get('set-cookie')).toContain('lead_log_session=abc');expect(res.headers.get('set-cookie')).not.toContain('Domain=');expect(res.headers.get('set-cookie')).toContain('HttpOnly');expect(res.headers.get('set-cookie')).toContain('Secure');expect(res.headers.get('set-cookie')).toContain('Path=/');expect(res.headers.get('set-cookie')).toContain('SameSite=Lax')});
 it('forwards register Set-Cookie',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:201,headers:{'set-cookie':'lead_log_session=reg; HttpOnly; Secure'}})) as typeof fetch;const res=await call(['api','v1','auth','register'],'/api/backend/api/v1/auth/register',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app','content-type':'application/json'},body:'{}'});expect(res.status).toBe(201);expect(res.headers.get('set-cookie')).toContain('lead_log_session=reg')});
 it('forwards session cookie to backend',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;await call(['api','v1','auth','session'],'/api/backend/api/v1/auth/session',{headers:{cookie:'lead_log_session=abc'}});const headers=vi.mocked(fetch).mock.calls[0][1]?.headers as Headers;expect(headers.get('cookie')).toBe('lead_log_session=abc')});
 it('proxies Today authenticated request to configured backend',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{"data":{"notes":[]}}',{status:200,headers:{'content-type':'application/json','cache-control':'no-store'}})) as typeof fetch;const res=await call(['api','v1','today'],'/api/backend/api/v1/today?x=1',{headers:{cookie:'lead_log_session=abc',accept:'application/json'}});expect(vi.mocked(fetch).mock.calls[0][0]?.toString()).toBe('https://lead-log-production.up.railway.app/api/v1/today?x=1');expect(res.headers.get('cache-control')).toBe('no-store')});
 it('forwards logout cookie clearing Set-Cookie and 204 body compatibility',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response(null,{status:204,headers:{'set-cookie':'lead_log_session=; Max-Age=0; HttpOnly; Secure; Path=/'}})) as typeof fetch;const res=await call(['api','v1','auth','logout'],'/api/backend/api/v1/auth/logout',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'}});expect(res.status).toBe(204);expect(await res.text()).toBe('');expect(res.headers.get('set-cookie')).toContain('Max-Age=0')});
 it('forwards backend 401 and 500 statuses',async()=>{global.fetch=vi.fn().mockResolvedValueOnce(new Response('{"error":{"code":"unauthorized"}}',{status:401})).mockResolvedValueOnce(new Response('{"error":{"code":"internal_error"}}',{status:500})) as typeof fetch;expect((await call(['api','v1','today'],'/api/backend/api/v1/today')).status).toBe(401);expect((await call(['api','v1','today'],'/api/backend/api/v1/today')).status).toBe(500)});
 it('returns 504 on request timeout',async()=>{vi.useFakeTimers();global.fetch=vi.fn((_url,init)=>new Promise((_resolve,reject)=>{(init?.signal as AbortSignal).addEventListener('abort',()=>reject(new DOMException('timeout','TimeoutError')))})) as typeof fetch;const pending=call(['api','v1','today'],'/api/backend/api/v1/today');await vi.advanceTimersByTimeAsync(15000);const res=await pending;expect(res.status).toBe(504);vi.useRealTimers()});
 it('rejects unsafe cross-origin requests',async()=>{global.fetch=vi.fn() as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'POST',headers:{origin:'https://evil.example'},body:'{}'});expect(res.status).toBe(403);expect(fetch).not.toHaveBeenCalled()});

 it('accepts exact configured production origin for unsafe requests',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{}'});expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('accepts localhost origin when configured',async()=>{vi.stubEnv('FRONTEND_ORIGIN','http://localhost:3000');global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'PUT',headers:{origin:'http://localhost:3000'},body:'{}'});expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('normalizes trailing slash on configured and request origins',async()=>{vi.stubEnv('FRONTEND_ORIGIN','https://lead-log-fe-production.up.railway.app/');global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','notes','1'],'/api/backend/api/v1/notes/1',{method:'PATCH',headers:{origin:'https://lead-log-fe-production.up.railway.app/'},body:'{}'});expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('rejects missing Origin on unsafe requests',async()=>{global.fetch=vi.fn() as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'DELETE',body:'{}'});expect(res.status).toBe(403);expect(fetch).not.toHaveBeenCalled()});
 it('does not require Origin for GET requests',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','today'],'/api/backend/api/v1/today');expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('does not behave as an open proxy',async()=>{global.fetch=vi.fn() as typeof fetch;const res=await call(['https:','evil.example','x'],'/api/backend/https:/evil.example/x');expect(res.status).toBe(404);expect(fetch).not.toHaveBeenCalled()});
 it('does not log sensitive data',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200,headers:{'set-cookie':'lead_log_session=secret; HttpOnly'}})) as typeof fetch;await call(['api','v1','auth','login'],'/api/backend/api/v1/auth/login',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app',cookie:'lead_log_session=secret'},body:'{"password":"secret"}'});expect(console.log).not.toHaveBeenCalled();expect(console.error).not.toHaveBeenCalled();expect(console.warn).not.toHaveBeenCalled();const messages=vi.mocked(console.info).mock.calls.map(call=>JSON.stringify(call));expect(messages.join(' ')).not.toContain('secret');expect(messages.join(' ')).not.toContain('lead_log_session');expect(messages.join(' ')).not.toContain('password')})
});
