import { describe,it,expect,vi,beforeEach,afterEach } from 'vitest';
import { NextRequest } from 'next/server';
import { proxyBackend } from './[...path]/route';

function req(path:string,init:RequestInit={}){const nextInit={...init,signal:init.signal??undefined};return new NextRequest(`https://lead-log-fe-production.up.railway.app${path}`,nextInit)}
function ctx(path:string[]){return {params:{path}}}
async function call(path:string[],requestPath:string,init:RequestInit={}){return proxyBackend(req(requestPath,init),ctx(path))}

beforeEach(()=>{vi.stubEnv('BACKEND_API_BASE_URL','https://lead-log-production.up.railway.app');vi.stubEnv('FRONTEND_ORIGIN','https://lead-log-fe-production.up.railway.app');vi.spyOn(console,'log').mockImplementation(()=>{});vi.spyOn(console,'error').mockImplementation(()=>{});vi.spyOn(console,'warn').mockImplementation(()=>{});vi.spyOn(console,'info').mockImplementation(()=>{})});
afterEach(()=>{vi.unstubAllEnvs();vi.restoreAllMocks()});

describe('backend BFF proxy',()=>{
 it('forwards login Set-Cookie for frontend origin without Domain',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{ok:true}}),{status:200,headers:{'content-type':'application/json','set-cookie':'lead_log_session=abc; Domain=lead-log-production.up.railway.app; HttpOnly; Secure; Path=/; SameSite=None'}})) as typeof fetch;const res=await call(['api','v1','auth','login'],'/api/backend/api/v1/auth/login',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app','content-type':'application/json'},body:'{"email":"a@b.com","password":"secretsecret"}'});expect(res.status).toBe(200);expect(res.headers.get('set-cookie')).toContain('lead_log_session=abc');expect(res.headers.get('set-cookie')).not.toContain('Domain=');expect(res.headers.get('set-cookie')).toContain('HttpOnly');expect(res.headers.get('set-cookie')).toContain('Secure');expect(res.headers.get('set-cookie')).toContain('Path=/');expect(res.headers.get('set-cookie')).toContain('SameSite=Lax')});
 it('forwards register Set-Cookie',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:201,headers:{'set-cookie':'lead_log_session=reg; HttpOnly; Secure'}})) as typeof fetch;const res=await call(['api','v1','auth','register'],'/api/backend/api/v1/auth/register',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app','content-type':'application/json'},body:'{}'});expect(res.status).toBe(201);expect(res.headers.get('set-cookie')).toContain('lead_log_session=reg')});
 it('forwards session cookie to backend',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;await call(['api','v1','auth','session'],'/api/backend/api/v1/auth/session',{headers:{cookie:'lead_log_session=abc'}});const headers=vi.mocked(fetch).mock.calls[0][1]?.headers as Headers;expect(headers.get('cookie')).toBe('lead_log_session=abc')});
 it('proxies Today authenticated request to configured backend',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{"data":{"notes":[]}}',{status:200,headers:{'content-type':'application/json','cache-control':'no-store'}})) as typeof fetch;const res=await call(['api','v1','today'],'/api/backend/api/v1/today?x=1',{headers:{cookie:'lead_log_session=abc',accept:'application/json'}});expect(vi.mocked(fetch).mock.calls[0][0]?.toString()).toBe('https://lead-log-production.up.railway.app/api/v1/today?x=1');expect(res.headers.get('cache-control')).toBe('no-store')});
 it('forwards logout cookie clearing Set-Cookie and 204 body compatibility',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response(null,{status:204,headers:{'set-cookie':'lead_log_session=; Max-Age=0; HttpOnly; Secure; Path=/'}})) as typeof fetch;const res=await call(['api','v1','auth','logout'],'/api/backend/api/v1/auth/logout',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'}});expect(res.status).toBe(204);expect(await res.text()).toBe('');expect(res.headers.get('set-cookie')).toContain('Max-Age=0')});
 it('forwards backend 401 and 500 statuses',async()=>{global.fetch=vi.fn().mockResolvedValueOnce(new Response('{"error":{"code":"unauthorized"}}',{status:401})).mockResolvedValueOnce(new Response('{"error":{"code":"internal_error"}}',{status:500})) as typeof fetch;expect((await call(['api','v1','today'],'/api/backend/api/v1/today')).status).toBe(401);expect((await call(['api','v1','today'],'/api/backend/api/v1/today')).status).toBe(500)});
 it('returns 504 on BFF request timeout',async()=>{vi.useFakeTimers();global.fetch=vi.fn((_url,init)=>new Promise((_resolve,reject)=>{(init?.signal as AbortSignal).addEventListener('abort',()=>reject(new DOMException('timeout','TimeoutError')))})) as typeof fetch;const promise=call(['api','v1','today'],'/api/backend/api/v1/today');await vi.advanceTimersByTimeAsync(15000);const res=await promise;expect(res.status).toBe(504);expect(await res.json()).toMatchObject({error:{code:'timeout'}});vi.useRealTimers()});

 it('uses the default timeout for ordinary GET and POST requests',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;await call(['api','v1','today'],'/api/backend/api/v1/today');await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{}'});const signals=vi.mocked(fetch).mock.calls.map(c=>c[1]?.signal as AbortSignal);expect(signals).toHaveLength(2);expect(signals.every(Boolean)).toBe(true);const logs=vi.mocked(console.info).mock.calls.map(call=>call[1]).filter(Boolean) as Array<Record<string,unknown>>;expect(logs).toEqual(expect.arrayContaining([expect.objectContaining({route:'/api/v1/today',timeout_class:'default',configured_timeout_ms:15000}),expect.objectContaining({route:'/api/v1/notes',timeout_class:'default',configured_timeout_ms:15000})]));});
 it('uses ask-specific timeout for exact ask POST',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;await call(['api','v1','ask'],'/api/backend/api/v1/ask',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{}'});expect(vi.mocked(console.info).mock.calls.map(call=>call[1])).toEqual(expect.arrayContaining([expect.objectContaining({route:'/api/v1/ask',timeout_class:'ask',configured_timeout_ms:60000})]));});
 it('lets summary generation run beyond default timeout and preserves backend status and body',async()=>{vi.useFakeTimers();global.fetch=vi.fn((_url,_init)=>new Promise(resolve=>setTimeout(()=>resolve(new Response('{"data":{"ok":true}}',{status:202,headers:{'content-type':'application/json'}})),16000))) as typeof fetch;const promise=call(['api','v1','summaries','generate'],'/api/backend/api/v1/summaries/generate',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app','content-type':'application/json'},body:'{}'});await vi.advanceTimersByTimeAsync(15000);expect((vi.mocked(fetch).mock.calls[0][1]?.signal as AbortSignal).aborted).toBe(false);await vi.advanceTimersByTimeAsync(1000);const res=await promise;expect(res.status).toBe(202);expect(await res.text()).toBe('{"data":{"ok":true}}');vi.useRealTimers()});
 it('times out summary generation at the extended deadline without logging request or response bodies',async()=>{vi.useFakeTimers();global.fetch=vi.fn((_url,init)=>new Promise((_resolve,reject)=>{(init?.signal as AbortSignal).addEventListener('abort',()=>reject(new DOMException('timeout','TimeoutError')))})) as typeof fetch;const promise=call(['api','v1','summaries','generate'],'/api/backend/api/v1/summaries/generate',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{"summary":"secret"}'});await vi.advanceTimersByTimeAsync(105000);const res=await promise;expect(res.status).toBe(504);expect(await res.json()).toMatchObject({error:{code:'timeout'}});const logs=vi.mocked(console.info).mock.calls.map(call=>JSON.stringify(call));expect(logs.join(' ')).toContain('summary_generation');expect(logs.join(' ')).not.toContain('secret');vi.useRealTimers()});
 it('propagates browser cancellation to downstream fetch separately from BFF timeout',async()=>{const controller=new AbortController();global.fetch=vi.fn((_url,init)=>new Promise((_resolve,reject)=>{(init?.signal as AbortSignal).addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')));queueMicrotask(()=>controller.abort())})) as typeof fetch;const request=req('/api/backend/api/v1/summaries/generate',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{}'});Object.defineProperty(request,'signal',{value:controller.signal});const res=await proxyBackend(request,ctx(['api','v1','summaries','generate']));expect(res.status).toBe(499);expect(vi.mocked(console.info).mock.calls.map(call=>call[1])).toEqual(expect.arrayContaining([expect.objectContaining({result:'client_aborted'})]));});
 it('uses long timeout only for exact summary generation POST',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;await call(['api','v1','summaries'],'/api/backend/api/v1/summaries');await call(['api','v1','summaries','123'],'/api/backend/api/v1/summaries/123');await call(['api','v1','summaries','generate'],'/api/backend/api/v1/summaries/generate');await call(['api','v1','summaries','generate'],'/api/backend/api/v1/summaries/generate',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{}'});const logs=vi.mocked(console.info).mock.calls.map(call=>call[1]).filter(Boolean) as Array<Record<string,unknown>>;expect(logs).toEqual(expect.arrayContaining([expect.objectContaining({route:'/api/v1/summaries',timeout_class:'default'}),expect.objectContaining({route:'/api/v1/summaries/123',timeout_class:'default'}),expect.objectContaining({route:'/api/v1/summaries/generate',method:'GET',timeout_class:'default'}),expect.objectContaining({route:'/api/v1/summaries/generate',method:'POST',timeout_class:'summary_generation'})]));});
 it('rejects invalid timeout configuration and configured summary timeouts shorter than backend summary timeout',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;vi.stubEnv('BFF_DEFAULT_TIMEOUT','0s');await expect(call(['api','v1','today'],'/api/backend/api/v1/today')).rejects.toThrow(/positive duration/);vi.stubEnv('BFF_DEFAULT_TIMEOUT','15s');vi.stubEnv('BFF_SUMMARY_GENERATION_TIMEOUT','90s');vi.stubEnv('BACKEND_SUMMARY_GENERATION_TIMEOUT','100s');await expect(call(['api','v1','summaries','generate'],'/api/backend/api/v1/summaries/generate',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{}'})).rejects.toThrow(/must be longer/);});

 it('rejects unsafe cross-origin requests',async()=>{global.fetch=vi.fn() as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'POST',headers:{origin:'https://evil.example'},body:'{}'});expect(res.status).toBe(403);expect(fetch).not.toHaveBeenCalled()});

 it('accepts exact configured production origin for unsafe requests',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app'},body:'{}'});expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('accepts localhost origin when configured',async()=>{vi.stubEnv('FRONTEND_ORIGIN','http://localhost:3000');global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'PUT',headers:{origin:'http://localhost:3000'},body:'{}'});expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('normalizes trailing slash on configured and request origins',async()=>{vi.stubEnv('FRONTEND_ORIGIN','https://lead-log-fe-production.up.railway.app/');global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','notes','1'],'/api/backend/api/v1/notes/1',{method:'PATCH',headers:{origin:'https://lead-log-fe-production.up.railway.app/'},body:'{}'});expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('rejects missing Origin on unsafe requests',async()=>{global.fetch=vi.fn() as typeof fetch;const res=await call(['api','v1','notes'],'/api/backend/api/v1/notes',{method:'DELETE',body:'{}'});expect(res.status).toBe(403);expect(fetch).not.toHaveBeenCalled()});
 it('does not require Origin for GET requests',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200})) as typeof fetch;const res=await call(['api','v1','today'],'/api/backend/api/v1/today');expect(res.status).toBe(200);expect(fetch).toHaveBeenCalled()});
 it('does not behave as an open proxy',async()=>{global.fetch=vi.fn() as typeof fetch;const res=await call(['https:','evil.example','x'],'/api/backend/https:/evil.example/x');expect(res.status).toBe(404);expect(fetch).not.toHaveBeenCalled()});
 it('does not log sensitive data',async()=>{global.fetch=vi.fn().mockResolvedValue(new Response('{}',{status:200,headers:{'set-cookie':'lead_log_session=secret; HttpOnly'}})) as typeof fetch;await call(['api','v1','auth','login'],'/api/backend/api/v1/auth/login',{method:'POST',headers:{origin:'https://lead-log-fe-production.up.railway.app',cookie:'lead_log_session=secret'},body:'{"password":"secret"}'});expect(console.log).not.toHaveBeenCalled();expect(console.error).not.toHaveBeenCalled();expect(console.warn).not.toHaveBeenCalled();const messages=vi.mocked(console.info).mock.calls.map(call=>JSON.stringify(call));expect(messages.join(' ')).not.toContain('secret');expect(messages.join(' ')).not.toContain('lead_log_session');expect(messages.join(' ')).not.toContain('password')})
});
