import { render,screen,waitFor,within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,it,expect,vi,beforeEach } from 'vitest';
import { NotesHistoryPage } from './notes-history-page';
import { api } from '@/lib/api/endpoints';
import type { NotesHistory,ProcessingStatus } from '@/lib/api/types';

let query='';const replace=vi.fn((url:string)=>{query=url.split('?')[1]??''});const push=vi.fn((url:string)=>{query=url.split('?')[1]??''});
vi.mock('next/navigation',()=>({useRouter:()=>({replace,push}),usePathname:()=>'/notes',useSearchParams:()=>new URLSearchParams(query)}));
vi.mock('@/lib/api/endpoints',()=>({api:{notesHistory:vi.fn(),note:vi.fn()}}));
const note=(id:string,created_at='2026-07-19T12:00:00Z',status:ProcessingStatus='processed')=>({id,raw_text:`Raw ${id} українська 🚀`,summary:`Summary ${id}`,processing_status:status,created_at,processed_at:null,extracted_counts:{actions:1,people:1,decisions:0,entities:0},preview:{people:[{id:'person_1',display_name:'Adlet'}],tickets:['CH-1234'],tags:['message-processor']}} as const);
const page=(items:any[],next_cursor:string|null=null):NotesHistory=>({items,page:{next_cursor,has_more:!!next_cursor}});
beforeEach(()=>{query='';replace.mockClear();push.mockClear();vi.mocked(api.notesHistory).mockReset();vi.mocked(api.note).mockReset();vi.mocked(api.note).mockResolvedValue({...note('note_1'),actions:[],people:[],decisions:[],entities:[]});});
describe('NotesHistoryPage',()=>{
 it('loads one initial page and renders notes, filters, statuses, metadata, and pagination',async()=>{vi.mocked(api.notesHistory).mockResolvedValueOnce(page([note('note_1'),note('note_2','2026-07-18T10:00:00Z','failed')],'cursor_2')).mockResolvedValueOnce(page([note('note_3','2026-07-17T10:00:00Z','pending'),note('note_1')],null));render(<NotesHistoryPage/>);expect(screen.getByRole('heading',{level:1,name:'Notes history'})).toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('Loading notes history');await screen.findByText('Summary note_1');expect(api.notesHistory).toHaveBeenCalledTimes(1);expect(api.notesHistory).toHaveBeenLastCalledWith({limit:20,cursor:undefined,query:undefined,status:undefined,from:undefined,to:undefined},expect.any(AbortSignal));expect(screen.getByLabelText('Search notes')).toBeInTheDocument();expect(screen.getByLabelText('From')).toBeInTheDocument();expect(screen.getByLabelText('To')).toBeInTheDocument();expect(screen.getByLabelText('Status')).toBeInTheDocument();expect(screen.getByText('Processing failed')).toBeInTheDocument();expect(screen.getAllByText('Adlet')[0]).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Load older notes'}));await screen.findByText('Summary note_3');expect(api.notesHistory).toHaveBeenLastCalledWith(expect.objectContaining({cursor:'cursor_2'}));expect(screen.getAllByText('Summary note_1')).toHaveLength(1);});
 it('initializes URL filters, omits all status, clears filters, and debounces valid search',async()=>{query='query=retry&status=failed&from=2026-07-01&to=2026-07-19';vi.mocked(api.notesHistory).mockResolvedValue(page([]));render(<NotesHistoryPage/>);await waitFor(()=>expect(api.notesHistory).toHaveBeenCalled());expect(api.notesHistory).toHaveBeenLastCalledWith(expect.objectContaining({query:'retry',status:'failed',from:'2026-07-01',to:'2026-07-19'}),expect.any(AbortSignal));expect(screen.getByDisplayValue('retry')).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText('Status'),'all');expect(push).toHaveBeenCalledWith('/notes?query=retry&from=2026-07-01&to=2026-07-19',{scroll:false});await userEvent.click(screen.getByRole('button',{name:/Remove Search/}));expect(push).toHaveBeenCalledWith('/notes?status=failed&from=2026-07-01&to=2026-07-19',{scroll:false});});
 it('opens detail without reloading the list and preserves list on detail error',async()=>{vi.mocked(api.notesHistory).mockResolvedValue(page([note('note_1')]));vi.mocked(api.note).mockRejectedValue(new Error('nope'));render(<NotesHistoryPage/>);await screen.findByText('Summary note_1');await userEvent.click(screen.getByRole('button',{name:/Open note/}));await screen.findByText('Unable to load note.');expect(screen.getByText('Summary note_1')).toBeInTheDocument();expect(api.notesHistory).toHaveBeenCalledTimes(1);expect(api.note).toHaveBeenCalledTimes(1);expect(screen.getByRole('complementary',{name:'Note details'})).toHaveClass('detail-panel','note-detail-panel','note-detail-open');});
 it('shows contextual empty and first-page error states',async()=>{vi.mocked(api.notesHistory).mockRejectedValueOnce(new Error('network'));const {rerender}=render(<NotesHistoryPage/>);await screen.findByRole('alert');expect(screen.getByText(/Something went wrong/)).toBeInTheDocument();vi.mocked(api.notesHistory).mockResolvedValue(page([]));await userEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByText('No notes yet');query='status=pending';rerender(<NotesHistoryPage/>);await screen.findByText('No notes match these filters');});
});
