import Link from 'next/link';
import { formatDateTime } from '@/lib/formatting/date';
import type { SummaryContent,SummaryItem,SummarySource,SummaryType } from '@/lib/api/types';
export const types:SummaryType[]=['daily','weekly'];export const dateRe=/^\d{4}-\d{2}-\d{2}$/;export const LIMIT=20;
export function cap(s:string,n=240){return s.length>n?`${s.slice(0,n)}…`:s}
export function labelType(t:SummaryType|string){return t==='weekly'?'Weekly':'Daily'}
function dateLabel(d:string){const [y,m,day]=d.split('-').map(Number);return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(Date.UTC(y,m-1,day)))}
export function periodLabel(p:{from:string;to:string}){return p.from===p.to?dateLabel(p.from):`${dateLabel(p.from)}–${dateLabel(p.to)}`}
export function freshness(s:boolean|null|undefined){return s===true?'Source notes changed':s===false?'Current':'Freshness unknown'}
export function StatusFresh({summary}:{summary:SummaryItem}){return <p className="summary-meta"><span className="chip">Status: {summary.status==='ready'?'Ready':summary.status}</span> <span className="chip">{freshness(summary.source_changed)}</span></p>}
export function SummaryCard({summary}:{summary:SummaryItem}){return <Link className="card summary-card" href={`/summaries/${encodeURIComponent(summary.id)}`}><div className="action-row"><div><p className="chip">{labelType(summary.type)} summary</p><h2>{summary.title||`${labelType(summary.type)} summary`}</h2></div></div><p className="summary-period">{periodLabel(summary.period)}</p><p className="muted summary-preview">{cap(summary.preview||'No preview available.')}</p><p className="muted">Generated {formatDateTime(summary.generated_at??null)}</p><StatusFresh summary={summary}/>{summary.source_changed&&<p className="error">Source notes changed. Open to review or regenerate.</p>}</Link>}
function textOf(v:unknown):string{if(v==null)return'';if(typeof v==='string')return v;if(typeof v==='number'||typeof v==='boolean')return String(v);if(Array.isArray(v))return v.map(textOf).filter(Boolean).join(' · ');if(typeof v==='object'){const o=v as Record<string,unknown>;return [o.text,o.title,o.summary,o.label,o.name,o.display_name,o.key,o.id].map(textOf).filter(Boolean).join(' — ')||''}return''}
function hrefFor(v:unknown){if(!v||typeof v!=='object')return null;const o=v as Record<string,unknown>;const person=typeof o.person_id==='string'?o.person_id:typeof o.id==='string'&&o.id.startsWith('person_')?o.id:null;const ticket=typeof o.ticket_key==='string'?o.ticket_key:typeof o.key==='string'?o.key:null;if(person)return `/people/${encodeURIComponent(person)}`;if(ticket)return `/tickets/${encodeURIComponent(ticket)}`;return null}
function Section({title,value}:{title:string;value:unknown}){if(value==null)return null;if(Array.isArray(value)&&!value.length)return null;if(typeof value==='string'&&!value.trim())return null;const items=Array.isArray(value)?value:[value];return <section className="summary-section"><h2>{title}</h2>{items.length===1&&typeof items[0]==='string'?<p className="preserve">{items[0]}</p>:<ul>{items.map((it,i)=>{const text=textOf(it);const href=hrefFor(it);return text?<li key={i}>{href?<Link href={href}>{text}</Link>:text}</li>:null})}</ul>}</section>}
export function SummaryContentView({type,content}:{type:SummaryType;content:SummaryContent}){if(content.text)return <Section title="Overview" value={content.text}/>;const daily:[string,keyof SummaryContent][]=[['Overview','short_summary'],['Highlights','highlights'],['Completed work','completed_work'],['Actions','actions'],['Decisions','decisions'],['People highlights','people_highlights'],['Tickets','tickets'],['Risks','risks'],['Open questions','open_questions'],['Open loops','open_loops'],['Suggested next steps','suggested_next_steps'],['Unclear items','unclear_items'],['Ticket candidates','ticket_candidates']];const weekly:[string,keyof SummaryContent][]=[['Weekly overview','weekly_overview'],['Outcomes','outcomes'],['Unresolved work','unresolved_work'],['Repeated topics','repeated_topics'],['Decisions','decisions'],['People','people'],['Tickets','tickets'],['Risks','risks'],['Next-week focus','next_week_focus'],['Open questions','open_questions']];const sections=(type==='daily'?daily:weekly).map(([t,k])=><Section key={k} title={t} value={content[k]}/>).filter(Boolean);return sections.length?<>{sections}</>:<p className="muted">This summary has no structured sections to display.</p>}
export function SummarySources({sources,onOpen}:{sources:SummarySource[];onOpen:(id:string,e:React.MouseEvent<HTMLButtonElement>)=>void}){if(!sources?.length)return null;return <section className="card section stack"><h2>Source notes</h2><ol className="source-list">{sources.map(s=><li key={s.id} className="source-card"><strong>{s.label||'Source note'}</strong><span className="muted"> · {formatDateTime(s.occurred_at)}</span><p className="muted excerpt">{cap(s.excerpt||'')}</p><button className="btn" onClick={e=>onOpen(s.id,e)}>Open source note</button></li>)}</ol></section>}
