import Link from 'next/link';
import { formatDateTime } from '@/lib/formatting/date';
import type { SummaryItem,SummarySource,SummaryType } from '@/lib/api/types';
import { clamp,dateLabelSafe,normalizeSummaryContent,summaryPreview,type NormalizedSummary,type NormalizedSummaryContent,type SummaryEntry } from './summary-normalization';
export const types:SummaryType[]=['daily','weekly'];export const dateRe=/^\d{4}-\d{2}-\d{2}$/;export const LIMIT=20;
export const cap=clamp;
export function labelType(t:SummaryType|string){return t==='weekly'?'Weekly':'Daily'}
export function periodLabel(p:{from:string;to:string}|null|undefined){if(!p)return 'Summary period unavailable';const from=dateLabelSafe(p.from),to=dateLabelSafe(p.to);if(!from||!to)return 'Summary period unavailable';return p.from===p.to?from:`${from}–${to}`}
export function freshness(s:boolean|null|undefined){return s===true?'Source notes changed':s===false?'Current':'Freshness unknown'}
export function StatusFresh({summary}:{summary:Pick<SummaryItem,'status'|'source_changed'>|Pick<NormalizedSummary,'status'|'source_changed'>}){return <p className="summary-meta"><span className="chip">Status: {summary.status==='ready'?'Ready':summary.status}</span> <span className="chip">{freshness(summary.source_changed)}</span></p>}
export function SummaryCard({summary}:{summary:SummaryItem}){return <Link className="card summary-card" href={`/summaries/${encodeURIComponent(summary.id)}`}><div className="action-row"><div><p className="chip">{labelType(summary.type)} summary</p><h2>{summary.title||`${labelType(summary.type)} summary`}</h2></div></div><p className="summary-period">{periodLabel(summary.period)}</p><p className="muted summary-preview">{summaryPreview(summary)}</p><p className="muted">Generated {formatDateTime(summary.generated_at??null)}</p><StatusFresh summary={summary}/>{summary.source_changed&&<p className="error">Source notes changed. Open to review or regenerate.</p>}</Link>}
function href(it:SummaryEntry){if(it.personId)return `/people/${encodeURIComponent(it.personId)}`;if(it.ticketKey)return `/tickets/${encodeURIComponent(it.ticketKey)}`;return undefined}
function Section({title,items}:{title:string;items:SummaryEntry[]}){if(!items.length)return null;return <section className="summary-section"><h2>{title}</h2><ul>{items.map(it=>{const h=href(it);return <li key={it.key}>{h?<Link href={h}>{it.primaryText}</Link>:it.primaryText}{it.secondaryText&&<p className="muted">{it.secondaryText}</p>}{it.sourceNoteIds.length>0&&<p className="muted">Sources: {it.sourceNoteIds.map(id=><span className="chip" key={id}>{id}</span>)}</p>}</li>})}</ul></section>}
function Paragraphs({text}:{text:string}){return <>{text.split(/\n{2,}|\n/).filter(Boolean).map((p,i)=><p key={i} className="preserve">{p}</p>)}</>}
function LegacySections({content}:{content:NonNullable<Extract<NormalizedSummaryContent,{kind:'legacy_text'}>['parsed']>}){return <><Section title="Highlights" items={content.highlights}/><Section title="Actions" items={content.actions}/><Section title="Decisions" items={content.decisions}/><Section title="People" items={content.people}/><Section title="Tickets" items={content.tickets}/><Section title="Risks" items={content.risks}/><Section title="Open questions" items={content.openQuestions}/><Section title="Repeated topics" items={content.repeatedTopics}/></>}
export function SummaryContentView({type,content,preview}:{type:SummaryType;content:unknown;preview?:string|null}){const n=normalizeSummaryContent(type,content as any);if(n.kind==='legacy_text')return <>{n.parsed?.summary?<section className="summary-section"><h2>Overview</h2><Paragraphs text={n.parsed.summary}/></section>:<section className="summary-section"><h2>Overview</h2><Paragraphs text={n.text}/></section>}{n.parsed&&<LegacySections content={n.parsed}/>}</>;if(n.kind==='unsupported')return <><p className="muted">This older summary uses a format that cannot be displayed fully.</p>{preview&&<Paragraphs text={summaryPreview({id:'preview',type,period:{from:'1970-01-01',to:'1970-01-01'},status:'ready',preview,content:content as any})}/>}</>;if(n.kind==='daily')return <>{n.overview&&<section className="summary-section"><h2>Overview</h2><Paragraphs text={n.overview}/></section>}<Section title="Highlights" items={n.highlights}/><Section title="Completed work" items={n.completedWork}/><Section title="Actions" items={n.actions}/><Section title="Decisions" items={n.decisions}/><Section title="People highlights" items={n.people}/><Section title="Tickets" items={n.tickets}/><Section title="Risks" items={n.risks}/><Section title="Open questions" items={n.openQuestions}/><Section title="Open loops" items={n.openLoops}/><Section title="Suggested next steps" items={n.suggestedNextSteps}/><Section title="Unclear items" items={n.unclearItems}/><Section title="Ticket candidates" items={n.ticketCandidates}/></>;return <>{n.overview&&<section className="summary-section"><h2>Weekly overview</h2><Paragraphs text={n.overview}/></section>}<Section title="Highlights" items={n.highlights}/><Section title="Actions" items={n.actions}/><Section title="Outcomes" items={n.outcomes}/><Section title="Unresolved work" items={n.unresolvedWork}/><Section title="Repeated topics" items={n.repeatedTopics}/><Section title="Decisions" items={n.decisions}/><Section title="People" items={n.people}/><Section title="Tickets" items={n.tickets}/><Section title="Risks" items={n.risks}/><Section title="Next-week focus" items={n.nextWeekFocus}/><Section title="Open questions" items={n.openQuestions}/></>}
export function SummarySources({sources,onOpen}:{sources:SummarySource[]|null|undefined;onOpen:(id:string,e:React.MouseEvent<HTMLButtonElement>)=>void}){const safe=sources??[];if(!safe.length)return null;return <section className="card section stack"><h2>Source notes</h2><ol className="source-list">{safe.map(s=><li key={s.id} className="source-card"><strong>{s.label||'Source note'}</strong><span className="muted"> · {formatDateTime(s.occurred_at)}</span><p className="muted excerpt">{cap(s.excerpt||'')}</p><button className="btn" onClick={e=>onOpen(s.id,e)}>Open source note</button></li>)}</ol></section>}
