import type { SummaryContent,SummaryItem,SummarySource,SummaryType } from '@/lib/api/types';


export type NormalizedSummaryPeriod={from:string;to:string};
export type NormalizedSummary={id:string;type:SummaryType;status:string;period:NormalizedSummaryPeriod|null;generated_at?:string|null;title?:string|null;preview?:string|null;source_changed?:boolean|null;content:SummaryContent;sources:SummarySource[];malformed?:boolean};
function obj(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==='object'&&!Array.isArray(v)}
export function isValidCalendarDate(value:unknown):value is string{return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&dateLabelSafe(value)!==null}
export function isValidCalendarDateRange(value:unknown):value is NormalizedSummaryPeriod{return obj(value)&&isValidCalendarDate(value.from)&&isValidCalendarDate(value.to)}
export function dateLabelSafe(d:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return null;const [y,m,day]=d.split('-').map(Number);const dt=new Date(Date.UTC(y,m-1,day));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==m-1||dt.getUTCDate()!==day)return null;return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(dt)}
export function normalizeSummary(apiSummary:unknown):NormalizedSummary|null{if(!obj(apiSummary))return null;const type=apiSummary.type==='weekly'?'weekly':apiSummary.type==='daily'?'daily':null;if(!type||typeof apiSummary.id!=='string')return null;const period=isValidCalendarDateRange(apiSummary.period)?{from:apiSummary.period.from,to:apiSummary.period.to}:null;const content=obj(apiSummary.content)?apiSummary.content as SummaryContent:{};const rawSources=Array.isArray(apiSummary.sources)?apiSummary.sources:[];const sources=rawSources.filter(obj).filter(s=>typeof s.id==='string').map(s=>({type:s.type==='note'?'note':'note',id:String(s.id),occurred_at:typeof s.occurred_at==='string'?s.occurred_at:'',label:typeof s.label==='string'?s.label:'Source note',excerpt:typeof s.excerpt==='string'?s.excerpt:''} satisfies SummarySource));return{id:apiSummary.id,type,status:typeof apiSummary.status==='string'?apiSummary.status:'ready',period,title:typeof apiSummary.title==='string'?apiSummary.title:null,preview:typeof apiSummary.preview==='string'?apiSummary.preview:null,generated_at:typeof apiSummary.generated_at==='string'?apiSummary.generated_at:null,source_changed:typeof apiSummary.source_changed==='boolean'?apiSummary.source_changed:null,content,sources,malformed:!period};}

export type SummaryListItem={key:string;primaryText:string;secondaryText?:string;sourceNoteIds:string[];personId?:string;ticketKey?:string;actionId?:string};
export type SummaryEntry=SummaryListItem;
export type NormalizedSummaryContent=
 |{kind:'daily';overview?:string;highlights:SummaryEntry[];completedWork:SummaryEntry[];actions:SummaryEntry[];decisions:SummaryEntry[];people:SummaryEntry[];tickets:SummaryEntry[];risks:SummaryEntry[];openQuestions:SummaryEntry[];openLoops:SummaryEntry[];suggestedNextSteps:SummaryEntry[];unclearItems:SummaryEntry[];ticketCandidates:SummaryEntry[]}
 |{kind:'weekly';overview?:string;outcomes:SummaryEntry[];unresolvedWork:SummaryEntry[];repeatedTopics:SummaryEntry[];decisions:SummaryEntry[];people:SummaryEntry[];tickets:SummaryEntry[];risks:SummaryEntry[];nextWeekFocus:SummaryEntry[];openQuestions:SummaryEntry[];highlights:SummaryEntry[];actions:SummaryEntry[]}
 |{kind:'legacy_text';text:string;parsed?:LegacyKnown}
 |{kind:'unsupported';fallback?:string};
export type LegacyKnown={summary?:string;highlights:SummaryEntry[];actions:SummaryEntry[];decisions:SummaryEntry[];people:SummaryEntry[];tickets:SummaryEntry[];risks:SummaryEntry[];openQuestions:SummaryEntry[];repeatedTopics:SummaryEntry[]};
const MAX_JSON=20000,FALLBACK='Summary item unavailable';
const knownLegacy=['summary','highlights','actions','decisions','people','tickets','risks','open_questions','repeated_topics'] as const;
function str(v:unknown){return typeof v==='string'&&v.trim()?v.trim():undefined}
function num(v:unknown){return typeof v==='number'&&Number.isFinite(v)?v:undefined}
function isPlainObject(v:unknown):v is Record<string,unknown>{return!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype}
function sourceIds(v:unknown){return Array.isArray(v)?v.map(x=>str(x)).filter((x):x is string=>!!x&&x.startsWith('note_')):[]}
function field(o:Record<string,unknown>,keys:string[]){return keys.map(k=>str(o[k])).find(Boolean)}
function idField(o:Record<string,unknown>,keys:string[]){return keys.map(k=>str(o[k])).find(Boolean)}
function baseKey(section:string,index:number,text:string){return `${section}-${index}-${text.slice(0,40)}`}
function entry(v:unknown,section='item',index=0):SummaryEntry|null{if(v==null)return null;if(typeof v==='string')return v.trim()?{key:baseKey(section,index,v.trim()),primaryText:v.trim(),sourceNoteIds:[]}:null;if(typeof v==='number'||typeof v==='boolean'){const text=String(v);return{key:baseKey(section,index,text),primaryText:text,sourceNoteIds:[]}}if(!isPlainObject(v))return null;
 const ticketKey=field(v,['ticket_key','canonical_key','key']);const personId=idField(v,['person_id','public_person_id']);const actionId=idField(v,['action_id','id'])?.startsWith('action_')?idField(v,['action_id','id']):undefined;
 const primary=field(v,['text','title','summary','label','display_name','name','description','question','risk','highlight','topic'])??ticketKey??FALLBACK;
 const count=num(v.occurrence_count)??num(v.count)??num(v.occurrences);const status=field(v,['status','state']);const owner=field(v,['owner','assignee']);
 const secondary=[count?`${count} occurrences`:undefined,status?`Status: ${status}`:undefined,owner?`Owner: ${owner}`:undefined].filter(Boolean).join(' · ')||undefined;
 return{key:idField(v,['id','action_id','person_id','ticket_key','key'])??baseKey(section,index,primary),primaryText:primary,secondaryText:secondary,sourceNoteIds:sourceIds(v.source_note_ids),personId,ticketKey,actionId};}
function entries(v:unknown,section:string):SummaryEntry[]{const raw=v==null?[]:Array.isArray(v)?v:[v];return raw.map((x,i)=>entry(x,section,i)).filter((x):x is SummaryEntry=>!!x)}
function safeJsonObject(text:string):Record<string,unknown>|null{const t=text.trim();if(t.length<2||t.length>MAX_JSON||!t.startsWith('{')||!t.endsWith('}'))return null;try{const parsed=JSON.parse(t);return isPlainObject(parsed)?parsed:null}catch{return null}}
export function parseLegacyKnownJson(text:string):LegacyKnown|null{const o=safeJsonObject(text);if(!o)return null;const hasKnown=knownLegacy.some(k=>Object.prototype.hasOwnProperty.call(o,k));if(!hasKnown)return null;return{summary:str(o.summary),highlights:entries(o.highlights,'highlights'),actions:entries(o.actions,'actions'),decisions:entries(o.decisions,'decisions'),people:entries(o.people,'people'),tickets:entries(o.tickets,'tickets'),risks:entries(o.risks,'risks'),openQuestions:entries(o.open_questions,'open_questions'),repeatedTopics:entries(o.repeated_topics,'repeated_topics')}}
function hasLegacy(l:LegacyKnown){return!!(l.summary||l.highlights.length||l.actions.length||l.decisions.length||l.people.length||l.tickets.length||l.risks.length||l.openQuestions.length||l.repeatedTopics.length)}
export function normalizeSummaryContent(type:SummaryType,content:SummaryContent|null|undefined):NormalizedSummaryContent{if(!content||!isPlainObject(content))return{kind:'unsupported'};const text=str(content.text);if(text){const parsed=parseLegacyKnownJson(text);return parsed&&hasLegacy(parsed)?{kind:'legacy_text',text,parsed}:{kind:'legacy_text',text}}
 if(type==='daily'){const overview=str(content.short_summary)??str(content.summary);const n={kind:'daily' as const,overview,highlights:entries(content.highlights,'highlights'),completedWork:entries(content.completed_work,'completed_work'),actions:entries(content.actions,'actions'),decisions:entries(content.decisions,'decisions'),people:entries(content.people_highlights,'people_highlights'),tickets:entries(content.tickets,'tickets'),risks:entries(content.risks,'risks'),openQuestions:entries(content.open_questions,'open_questions'),openLoops:entries(content.open_loops,'open_loops'),suggestedNextSteps:entries(content.suggested_next_steps,'suggested_next_steps'),unclearItems:entries(content.unclear_items,'unclear_items'),ticketCandidates:entries(content.ticket_candidates,'ticket_candidates')};return overview||Object.values(n).some(v=>Array.isArray(v)&&v.length)?n:{kind:'unsupported'};}
 const overview=str(content.summary)??str(content.weekly_overview);const n={kind:'weekly' as const,overview,outcomes:entries(content.outcomes,'outcomes'),unresolvedWork:entries(content.unresolved_work,'unresolved_work'),repeatedTopics:entries(content.repeated_topics,'repeated_topics'),decisions:entries(content.decisions,'decisions'),people:entries(content.people,'people'),tickets:entries(content.tickets,'tickets'),risks:entries(content.risks,'risks'),nextWeekFocus:entries(content.next_week_focus,'next_week_focus'),openQuestions:entries(content.open_questions,'open_questions'),highlights:entries(content.highlights,'highlights'),actions:entries(content.actions,'actions')};return overview||Object.values(n).some(v=>Array.isArray(v)&&v.length)?n:{kind:'unsupported'};}
function readablePreview(s:string){const t=s.trim();return !(t.startsWith('{')&&t.includes('"'))&&!/[{}]"?summary"?\s*:/.test(t)}
export function summaryPreview(summary:SummaryItem&{content?:SummaryContent|null}){const api=str(summary.preview);if(api&&readablePreview(api))return clamp(api);const parsedApi=api?parseLegacyKnownJson(api):null;if(parsedApi?.summary)return clamp(parsedApi.summary);const n=normalizeSummaryContent(summary.type,summary.content);if(n.kind==='daily'||n.kind==='weekly')return clamp(n.overview||first(n)||'No preview available.');if(n.kind==='legacy_text'){if(n.parsed?.summary)return clamp(n.parsed.summary);return clamp(n.text)}return clamp(parsedApi?.summary||'This older summary uses a format that cannot be displayed fully.');}
function first(n:Extract<NormalizedSummaryContent,{kind:'daily'|'weekly'}>){for(const v of Object.values(n))if(Array.isArray(v)&&v[0])return v[0].primaryText;return undefined}
export function clamp(s:string,n=240){return s.length>n?`${Array.from(s).slice(0,n).join('')}…`:s}
