import type { SummaryContent,SummaryItem,SummaryType } from '@/lib/api/types';

export type SummaryEntry={text:string;href?:string};
export type NormalizedSummaryContent=
 |{kind:'daily';overview?:string;highlights:SummaryEntry[];completedWork:SummaryEntry[];actions:SummaryEntry[];decisions:SummaryEntry[];people:SummaryEntry[];tickets:SummaryEntry[];risks:SummaryEntry[];openQuestions:SummaryEntry[];openLoops:SummaryEntry[];suggestedNextSteps:SummaryEntry[];unclearItems:SummaryEntry[];ticketCandidates:SummaryEntry[]}
 |{kind:'weekly';overview?:string;outcomes:SummaryEntry[];unresolvedWork:SummaryEntry[];repeatedTopics:SummaryEntry[];decisions:SummaryEntry[];people:SummaryEntry[];tickets:SummaryEntry[];risks:SummaryEntry[];nextWeekFocus:SummaryEntry[];openQuestions:SummaryEntry[]}
 |{kind:'legacy_text';text:string;parsed?:LegacyKnown}
 |{kind:'unsupported';fallback?:string};
export type LegacyKnown={summary?:string;highlights:SummaryEntry[];actions:SummaryEntry[];decisions:SummaryEntry[];people:SummaryEntry[];tickets:SummaryEntry[];risks:SummaryEntry[];openQuestions:SummaryEntry[];repeatedTopics:SummaryEntry[]};
const MAX_JSON=20000;
const knownLegacy=['summary','highlights','actions','decisions','people','tickets','risks','open_questions','repeated_topics'] as const;
function str(v:unknown){return typeof v==='string'&&v.trim()?v.trim():undefined}
function isPlainObject(v:unknown):v is Record<string,unknown>{return!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype}
function hrefFor(o:Record<string,unknown>){const person=str(o.person_id)??(str(o.id)?.startsWith('person_')?str(o.id):undefined);const ticket=str(o.ticket_key)??str(o.key);if(person)return `/people/${encodeURIComponent(person)}`;if(ticket)return `/tickets/${encodeURIComponent(ticket)}`;return undefined}
function entry(v:unknown):SummaryEntry|null{if(typeof v==='string')return v.trim()?{text:v.trim()}:null;if(typeof v==='number'||typeof v==='boolean')return {text:String(v)};if(isPlainObject(v)){const text=[v.text,v.title,v.summary,v.label,v.name,v.display_name,v.key].map(str).find(Boolean);return text?{text,href:hrefFor(v)}:null}return null}
function entries(v:unknown):SummaryEntry[]{if(v==null)return[];if(Array.isArray(v))return v.map(entry).filter((x):x is SummaryEntry=>!!x);const one=entry(v);return one?[one]:[]}
function safeJsonObject(text:string):Record<string,unknown>|null{const t=text.trim();if(t.length<2||t.length>MAX_JSON||!t.startsWith('{')||!t.endsWith('}'))return null;try{const parsed=JSON.parse(t);return isPlainObject(parsed)?parsed:null}catch{return null}}
export function parseLegacyKnownJson(text:string):LegacyKnown|null{const o=safeJsonObject(text);if(!o)return null;const hasKnown=knownLegacy.some(k=>Object.prototype.hasOwnProperty.call(o,k));if(!hasKnown)return null;return{summary:str(o.summary),highlights:entries(o.highlights),actions:entries(o.actions),decisions:entries(o.decisions),people:entries(o.people),tickets:entries(o.tickets),risks:entries(o.risks),openQuestions:entries(o.open_questions),repeatedTopics:entries(o.repeated_topics)}}
function hasLegacy(l:LegacyKnown){return!!(l.summary||l.highlights.length||l.actions.length||l.decisions.length||l.people.length||l.tickets.length||l.risks.length||l.openQuestions.length||l.repeatedTopics.length)}
export function normalizeSummaryContent(type:SummaryType,content:SummaryContent|null|undefined):NormalizedSummaryContent{if(!content||!isPlainObject(content))return{kind:'unsupported'};const text=str(content.text);if(text){const parsed=parseLegacyKnownJson(text);return parsed&&hasLegacy(parsed)?{kind:'legacy_text',text,parsed}:{kind:'legacy_text',text}}
 if(type==='daily'){const overview=str(content.short_summary);const n={kind:'daily' as const,overview,highlights:entries(content.highlights),completedWork:entries(content.completed_work),actions:entries(content.actions),decisions:entries(content.decisions),people:entries(content.people_highlights),tickets:entries(content.tickets),risks:entries(content.risks),openQuestions:entries(content.open_questions),openLoops:entries(content.open_loops),suggestedNextSteps:entries(content.suggested_next_steps),unclearItems:entries(content.unclear_items),ticketCandidates:entries(content.ticket_candidates)};return overview||Object.values(n).some(v=>Array.isArray(v)&&v.length)?n:{kind:'unsupported'};}
 const overview=str(content.weekly_overview);const n={kind:'weekly' as const,overview,outcomes:entries(content.outcomes),unresolvedWork:entries(content.unresolved_work),repeatedTopics:entries(content.repeated_topics),decisions:entries(content.decisions),people:entries(content.people),tickets:entries(content.tickets),risks:entries(content.risks),nextWeekFocus:entries(content.next_week_focus),openQuestions:entries(content.open_questions)};return overview||Object.values(n).some(v=>Array.isArray(v)&&v.length)?n:{kind:'unsupported'};}
function readablePreview(s:string){const t=s.trim();return !(t.startsWith('{')&&t.includes('"'))&&!/[{}]"?summary"?\s*:/.test(t)}
export function summaryPreview(summary:SummaryItem&{content?:SummaryContent|null}){const api=str(summary.preview);if(api&&readablePreview(api))return clamp(api);const parsedApi=api?parseLegacyKnownJson(api):null;if(parsedApi?.summary)return clamp(parsedApi.summary);const n=normalizeSummaryContent(summary.type,summary.content);if(n.kind==='daily'||n.kind==='weekly')return clamp(n.overview||first(n)||'No preview available.');if(n.kind==='legacy_text'){if(n.parsed?.summary)return clamp(n.parsed.summary);return clamp(n.text)}return clamp(parsedApi?.summary||'This older summary uses a format that cannot be displayed fully.');}
function first(n:Extract<NormalizedSummaryContent,{kind:'daily'|'weekly'}>){for(const v of Object.values(n))if(Array.isArray(v)&&v[0])return v[0].text;return undefined}
export function clamp(s:string,n=240){return s.length>n?`${Array.from(s).slice(0,n).join('')}…`:s}
