import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,it,expect,vi,beforeEach } from 'vitest';
import { PeoplePage } from './people-page';
import { api } from '@/lib/api/endpoints';
import type { PeopleList } from '@/lib/api/types';
let query='';const replace=vi.fn((url:string)=>{query=url.split('?')[1]??''});const push=vi.fn((url:string)=>{query=url.split('?')[1]??''});
vi.mock('next/navigation',()=>({useRouter:()=>({replace,push}),usePathname:()=>'/people',useSearchParams:()=>new URLSearchParams(query)}));
vi.mock('@/lib/api/endpoints',()=>({api:{people:vi.fn()}}));
const person=(id:string,name='Adlet')=>({id,display_name:name,aliases:['Адлет'],last_mentioned_at:'2026-07-18T13:42:00Z',mention_count:14,open_action_count:2,recent_note:{id:'note_184',created_at:'2026-07-18T13:42:00Z',summary:'Discussed retry policy and ownership.'}});
const page=(items:any[],next_cursor:string|null=null):PeopleList=>({items,page:{next_cursor,has_more:!!next_cursor}});
beforeEach(()=>{query='';replace.mockClear();push.mockClear();vi.useRealTimers();vi.mocked(api.people).mockReset();});
describe('PeoplePage',()=>{
 it('shows skeleton, makes one initial request, and renders people without per-card calls',async()=>{vi.mocked(api.people).mockResolvedValue(page([person('person_1')],'cursor_2'));const {rerender}=render(<PeoplePage/>);expect(screen.getByRole('heading',{level:1,name:'People'})).toBeInTheDocument();expect(screen.getByRole('status')).toHaveClass('people-grid');expect(screen.getByRole('status')).toHaveTextContent('Loading people');await screen.findByText('Adlet');expect(document.querySelector('.people-grid')).toBeInTheDocument();expect(document.querySelector('.person-card')).toBeInTheDocument();expect(api.people).toHaveBeenCalledTimes(1);expect(api.people).toHaveBeenLastCalledWith({limit:20,cursor:undefined,query:undefined,has_open_actions:undefined},expect.any(AbortSignal));expect(screen.getByText('Alias: Адлет')).toBeInTheDocument();expect(screen.getByText('14 mentions')).toBeInTheDocument();expect(screen.getByText(/Last mentioned:/)).toBeInTheDocument();expect(screen.getByText('2 open actions')).toBeInTheDocument();expect(screen.getByText('Discussed retry policy and ownership.')).toBeInTheDocument();expect(screen.getByRole('link',{name:/Adlet/})).toHaveAttribute('href','/people/person_1');rerender(<PeoplePage/>);expect(api.people).toHaveBeenCalledTimes(1);});
 it('initializes filters from URL, debounces search, clears search, and preserves private query from logs',async()=>{query='query=Adlet&has_open_actions=true';vi.mocked(api.people).mockResolvedValue(page([person('person_1')]));render(<PeoplePage/>);await waitFor(()=>expect(api.people).toHaveBeenCalled());expect(api.people).toHaveBeenLastCalledWith(expect.objectContaining({query:'Adlet',has_open_actions:true}),expect.any(AbortSignal));expect(screen.getByDisplayValue('Adlet')).toBeInTheDocument();expect(screen.getByLabelText('Only people with open actions')).toBeChecked();await userEvent.type(screen.getByLabelText('Search people'),'x');expect(replace).not.toHaveBeenCalledWith('/people?query=Adletx&has_open_actions=true',{scroll:false});await waitFor(()=>expect(replace).toHaveBeenCalledWith('/people?query=Adletx&has_open_actions=true',{scroll:false}),{timeout:800});await userEvent.click(screen.getByRole('button',{name:'Clear'}));expect(push).toHaveBeenCalledWith('/people?has_open_actions=true',{scroll:false});});
 it('paginates with opaque cursor, appends, deduplicates, blocks duplicate clicks, and retries next-page errors',async()=>{vi.mocked(api.people).mockResolvedValueOnce(page([person('person_1')],'cursor_2')).mockImplementationOnce(()=>new Promise(r=>setTimeout(()=>r(page([person('person_2','Mira'),person('person_1')],null)),20)) as any);render(<PeoplePage/>);await screen.findByText('Adlet');const btn=screen.getByRole('button',{name:'Load more people'});await userEvent.dblClick(btn);expect(api.people).toHaveBeenCalledTimes(2);await screen.findByText('Mira');expect(screen.getAllByText('Adlet')).toHaveLength(1);expect(api.people).toHaveBeenLastCalledWith(expect.objectContaining({cursor:'cursor_2'}));expect(screen.queryByRole('button',{name:'Load more people'})).not.toBeInTheDocument();});
 it('shows contextual empty and error states',async()=>{vi.mocked(api.people).mockRejectedValueOnce(new Error('network'));const {rerender}=render(<PeoplePage/>);await screen.findByRole('alert');expect(screen.getByText(/Something went wrong/)).toBeInTheDocument();vi.mocked(api.people).mockResolvedValue(page([]));await userEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByText('No people found yet');query='query=zz';rerender(<PeoplePage/>);await screen.findByText('No people match these filters');});
});
