import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,it,expect,vi,beforeEach } from 'vitest';
import { ApiRequestError } from '@/lib/api/client';
import { PersonDetailPage } from './person-detail-page';
import { api } from '@/lib/api/endpoints';
import type { PersonWorkspaceDetail,NoteDetail } from '@/lib/api/types';
vi.mock('@/lib/api/endpoints',()=>({api:{person:vi.fn(),updatePerson:vi.fn(),updateAction:vi.fn(),note:vi.fn()}}));
const detail=():PersonWorkspaceDetail=>({person:{id:'person_1',display_name:'Adlet',aliases:['Адлет'],first_mentioned_at:'2026-03-12T10:00:00Z',last_mentioned_at:'2026-07-18T13:42:00Z',mention_count:14,updated_at:'2026-07-18T13:43:00Z',first_name:'Adlet',last_name:'Khan',job_title:'Engineering Manager',team:'Platform',company:'Lead Log',notes:'Prefers async updates.'},open_actions:[{id:'action_1',title:'Follow up on retry policy',status:'open',linked_person:{display_name:'Adlet'},due_at:'2026-07-17T09:00:00Z',created_at:'2026-07-16T09:00:00Z',completed_at:null,source_note_id:'note_1'}],recent_decisions:[{id:'decision_1',text:'Use bounded retries.',status:'active',topic:'Retry policy'}],recent_notes:[{id:'note_1',created_at:'2026-07-18T13:42:00Z',summary:'Discussed retry policy.',raw_text_preview:'Raw preview',processing_status:'processed',tickets:['CH-1234']}],page:{next_cursor:null,has_more:false}});
const note:NoteDetail={id:'note_1',raw_text:'Raw note',summary:'Full summary',processing_status:'processed',created_at:'2026-07-18T13:42:00Z',processed_at:null,actions:[],people:[],decisions:[],entities:[]};
beforeEach(()=>{vi.mocked(api.person).mockReset();vi.mocked(api.updatePerson).mockReset();vi.mocked(api.updateAction).mockReset();vi.mocked(api.note).mockReset();vi.mocked(api.note).mockResolvedValue(note);});
describe('PersonDetailPage',()=>{
 it('renders profile sections and opens shared note details without reloading person',async()=>{vi.mocked(api.person).mockResolvedValue(detail());render(<PersonDetailPage personId="person_1"/>);expect(screen.getByRole('status')).toHaveTextContent('Loading person');await screen.findByRole('heading',{level:1,name:'Adlet'});expect(screen.getByText('Адлет')).toBeInTheDocument();expect(screen.getByText(/First mentioned:/)).toBeInTheDocument();expect(screen.getByText('14 mentions')).toBeInTheDocument();expect(screen.getByText('Follow up on retry policy')).toBeInTheDocument();expect(screen.getByText('Use bounded retries.')).toBeInTheDocument();expect(screen.getByText('Discussed retry policy.')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:/Open source note/}));await screen.findByRole('heading',{level:2,name:'Note details'});expect(api.note).toHaveBeenCalledTimes(1);expect(api.person).toHaveBeenCalledTimes(1);await userEvent.click(screen.getByRole('button',{name:'Close details'}));expect(screen.getByRole('heading',{level:1,name:'Adlet'})).toBeInTheDocument();});
 it('completes an action locally and shows section-level mutation failures',async()=>{vi.mocked(api.person).mockResolvedValue(detail());vi.mocked(api.updateAction).mockResolvedValueOnce({...detail().open_actions[0],status:'done',completed_at:'2026-07-18T14:00:00Z'});render(<PersonDetailPage personId="person_1"/>);await screen.findByText('Follow up on retry policy');await userEvent.click(screen.getByRole('button',{name:/Complete action/}));await waitFor(()=>expect(screen.queryByText('Follow up on retry policy')).not.toBeInTheDocument());expect(screen.getByText('Use bounded retries.')).toBeInTheDocument();vi.mocked(api.updateAction).mockRejectedValueOnce(new Error('nope'));});

 it('opens editor, validates aliases, saves changed fields, and restores focus',async()=>{vi.mocked(api.person).mockResolvedValue(detail());vi.mocked(api.updatePerson).mockResolvedValue({person:{...detail().person,display_name:'Adlet Updated',aliases:[],first_name:null,updated_at:'2026-07-18T15:00:00Z'}});render(<PersonDetailPage personId="person_1"/>);await screen.findByRole('heading',{level:1,name:'Adlet'});expect(screen.getByText('Engineering Manager')).toBeInTheDocument();expect(screen.getByText('Prefers async updates.')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Edit profile'}));expect(screen.getByRole('dialog',{name:'Edit profile'})).toBeInTheDocument();expect(screen.getByLabelText(/Display name/i)).toHaveFocus();await userEvent.clear(screen.getByLabelText(/Display name/i));expect(screen.getByRole('button',{name:'Save profile'})).toBeEnabled();await userEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText('Display name is required.')).toBeInTheDocument();await userEvent.type(screen.getByLabelText(/Display name/i),'Adlet Updated');await userEvent.type(screen.getByLabelText('New alias'),' Адлет ');await userEvent.click(screen.getByRole('button',{name:'Add alias'}));expect(screen.getByText('This alias is already listed.')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Remove alias Адлет'}));await userEvent.clear(screen.getByLabelText(/First Name/i));await userEvent.click(screen.getByRole('button',{name:'Save profile'}));await waitFor(()=>expect(api.updatePerson).toHaveBeenCalledWith('person_1',expect.objectContaining({expected_updated_at:'2026-07-18T13:43:00Z',display_name:'Adlet Updated',first_name:null,aliases:[]})));await screen.findByRole('heading',{level:1,name:'Adlet Updated'});expect(screen.getByRole('status')).toHaveTextContent('Profile updated.');expect(screen.getByRole('button',{name:'Edit profile'})).toHaveFocus();});
 it('keeps edited values visible after conflicts and blocks Escape when dirty',async()=>{vi.mocked(api.person).mockResolvedValue(detail());vi.mocked(api.updatePerson).mockRejectedValue(new ApiRequestError({kind:'conflict',status:409,message:'safe',fields:{expected_updated_at:'stale'}}));render(<PersonDetailPage personId="person_1"/>);await screen.findByRole('heading',{level:1,name:'Adlet'});await userEvent.click(screen.getByRole('button',{name:'Edit profile'}));await userEvent.clear(screen.getByLabelText(/Display name/i));await userEvent.type(screen.getByLabelText(/Display name/i),'Changed');await userEvent.keyboard('{Escape}');expect(screen.getByRole('dialog',{name:'Edit profile'})).toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('Use Cancel to discard');await userEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText(/changed since you opened/)).toBeInTheDocument();expect(screen.getByLabelText(/Display name/i)).toHaveValue('Changed');});

 it('handles empty sections, 404, and retryable errors',async()=>{vi.mocked(api.person).mockResolvedValue({...detail(),open_actions:[],recent_decisions:[],recent_notes:[]});const {rerender}=render(<PersonDetailPage personId="person_1"/>);await screen.findByText('No open actions linked to this person.');expect(screen.getByText('No recent decisions linked to this person.')).toBeInTheDocument();expect(screen.getByText('No recent notes linked to this person.')).toBeInTheDocument();vi.mocked(api.person).mockRejectedValue(new ApiRequestError({kind:'not_found',status:404,message:'no'}));rerender(<PersonDetailPage personId="person_2"/>);await screen.findByRole('heading',{level:1,name:'Person not found'});vi.mocked(api.person).mockRejectedValueOnce(new Error('network')).mockResolvedValueOnce(detail());rerender(<PersonDetailPage personId="person_3"/>);await screen.findByRole('button',{name:'Retry'});await userEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByRole('heading',{level:1,name:'Adlet'});});
});
